== Chapter II

His voyage to Barbados,
and labours there and at the adjacent Islands--Voyage from there to Ireland.

After I had settled my outward concerns, and placed my dear children to be taken care of,
until it pleased God that we should meet again,
I left my habitation on the 13th day of the fifth month, 1748,
having been on that day at a large meeting in our city, with Samuel Nottingham,
a Friend from Northamptonshire, in Old England, who was to be my companion.
We came with a great number of our very loving friends to Chester,
had a solid meeting there that evening, lodged at our worthy friend Grace Lloyd`'s,
and next morning taking leave of our beloved friends,
we went on board the vessel and set sail for Barbados.
On the passage I met with near trials in spirit,
and was at times almost overwhelmed by deep conflicts of soul.
Through the kindness and mercy of God we arrived safe at Barbados,
on the 21st day of the sixth month;
where we met with several Friends who were kind and loving toward us;
our dear friend Joseph Gamble took us to his house,
where we lodged for the most part of the time.
After we had attended meetings at Bridgetown, the Lord being with us,
enabled us by his mighty power to bear a faithful testimony, I trust,
to his eternal Truth, we went to Speightstown,
where we were favoured with some solid edifying meetings,
though not so large as at Bridgetown;
we lodged at our esteemed friend Edward Harrison`'s.

We were also at the Spring meetinghouse, lodged with a Friend living therein,
and next day had a meeting there, and in the afternoon at Bridgetown,
which was large and ended well.
We were on this island twenty-one days, and having seen Friends generally,
and been favoured with several edifying seasons,
we departed from there with Captain Austin, to Antigua, in our way to Tortola.
We stayed one week and a day at Antigua, lodged at James Birket`'s,
who was very kind to us;
but my mind was much burdened and distressed for that place and people,
who are for the most part a wicked and sinful generation.
We had no meeting among them, there being no Friend on the island, except Friend Birket,
and no openness, that I could find to satisfaction,
for the testimony of Truth to be declared, only we had some solid conversation with some.
I came away much bowed in spirit for the sins of the wicked in that island.
From there we went for Tortola, landed on the 28th of the seventh month,
and met with several Friends in the evening, at the house of our friend John Pickering,
who were glad to see us; where, and at our friend William Thomas`'s,
we lodged most of the time we were upon that island,
they being truly kind and friendly to us.
We were favoured with many good edifying meetings among Friends,
there being two meetinghouses on the island, namely, one at a place called Fat-hog bay,
the other at the Road.
We attended both of them with diligence, near the space of six weeks,
only that we were once at an island called Joes-Vandikes,
where we had a large good meeting.

On the 9th day of the ninth month, we left Tortola, in order to return to Antigua,
with design to get a passage for England; but being in a vessel,
the captain of which knew not how to manage her, we were going a contrary course,
in which if we had proceeded, we might all have been lost.
We were much tossed and driven about, and through persuasions,
we prevailed with the captain to turn back, and he brought us to Santa Croix;
but our going into the harbour called Lime Trees to drop anchor,
seemed as if it would have proved fatal to us, there lying a vessel armed with guns,
from which we were fired at three times, and my companion had like to have been shot.
It seems they had a design to have sunk our vessel,
having heard there was a Spanish privateer on the coast,
and the Governor had given orders to keep her off.
They suspected ours to be that vessel; but our mariners being in a great fright,
made signals that we had no ill design; when seeing we were in distress,
they forbore firing,
and through the kind deliverance of the Almighty we got safe in and dropped anchor.
Praised and worshipped be the name of God, that was nigh at hand,
and a present help in the time of need!
May I forever adore his great and eminent name, with all the true in heart,
throughout all generations!
He will not allow those to be confounded who trust in him,
and desire and endeavour faithfully to serve him.
A particular case concerning privateering, sometime before I left home,
now comes into my mind to mention.
Some great men of our city being concerned in fitting out vessels for that wicked business,
which having brought a deep engagement on my mind, it came upon me as a weighty duty,
to go to one of these men,
faithfully to warn him against this unrighteous way of getting riches.
I got a friend to accompany me, and I cleared my spirit of a heavy burden;
he pleaded for the practice, but used me civilly.
A new vessel was fitted out sometime after, called the Tartar,
which was much talked of to do great matters in privateering; but,
as I have been informed, she sunk before she got to sea,
and many or most of the people on board were drowned.
I had peace of mind for having discharged my duty,
although I much lamented the unhappy circumstances of those poor fellow mortals,
losing their lives in such an evil undertaking.

But to return to the place where we came to an anchor.--My
companion went on shore at Santa Croix,
and would have had me gone with him, but my mind being at that time much dejected,
I chose to stay on board the vessel until next morning, when I went on shore,
and met with my companion, who had agreed with a captain of a vessel,
bound for Spanishtown, near Tortola, for our passage there.
We put our chests and other things on board this vessel, then went on shore,
and travelled across the island on foot to Bas End harbour, where the vessel was to go,
choosing rather so to do, than to go round by water.
In our walk we met with people that were kind to us;
about noon we called at a house and dined, and were entertained in a friendly manner;
taking leave here, we went on towards Bas End,
stopping at another house some distance from the town for a drink of water.
The people seeing we were strangers, and being acquainted with Friends,
kindly invited us in, to stay with them until the vessel came round to the harbour,
and informed us that there was no house in the town suitable for us to be at,
which I found afterwards was true, for they seemed to be a very wicked people.

We stayed with these kind people two nights and a part of two days,
and on leaving them we would have satisfied them for the time we were there;
but they would not take anything for our entertainment,
and seemed well pleased with our company.
The man of the house attended us to the water side to see
us embark on board the vessel we had been waiting for,
where he parted with us in a friendly manner.
I waited a while on the shore for the captain to go on board, there being a vendue,
and a great number of people gathered to it; among them the Governor of the place,
being an island subject to the king of Denmark, I have since thought,
had we used endeavours, we might have had a meeting among them,
and I have wished it had happened so,
for I have at times been desirous in a solemn manner for the welfare of that people.
It is a fruitful island, and as good land I think as any I saw in all my travels,
could it be inhabited by men of religious minds,
so as to be fruitful to the heavenly Father,
who is willing to do good to mankind in general; but oh! the islands hereaway,
how great and many are the sins of the people,
mournful has been my soul for their many abominations.

We set sail, and arrived at Tortola on the 15th of the ninth month.
The captain and sailors were a wicked company, took some of our things from us,
and demanded considerable more for our passage than we had agreed for,
which we thought unreasonable.
They said we could afford to pay, for that we were always going about;
we told them we had the more need to be saving of what we had.
They hoisted out the boat in an angry manner,
and we paid them more than our passage to put us on shore.
They took us some distance from any house, and then landed us,
which put us to the more difficulty what to do with our chests and other necessaries,
that they might be safe; but being seen by one Isaac Pickering,
a kinsman to our friend John Pickering, he sent his lad to ask us to his house,
where we went.
He was so kind as to send for our things, took care of them,
and lent us horses to go to his uncle`'s that night, where we were kindly received,
and tenderly sympathized with on the disappointment and trouble we had met with;
they were dear and affectionate friends to us on this island.

We were at a meeting at Fat Hog Bay, the 16th of the ninth month,
and on the fourth day following, I was at one at the Road,
both of them were good meetings.
On the 23rd of the month,
I was taken ill of a fever at the house of our friend Thomas Humphreys,
and the next day my kind friend John Pickering brought
a man and horse and took me to his house,
where I remained very ill several weeks.
Some of the time I apprehended I should lay down my life among them;
but it was the blessed will of the Lord to restore me again to some degree of strength,
and I attended several meetings with Friends, wherein I had satisfaction.

On the 8th day of the eleventh month, I went to Gwan island,
with our friends James Parke and his wife, and stayed till the 11th of the same.
After having a comfortable time in his family, I returned to Tortola,
it being the meeting day at Fat Hog Bay, and it proved to be a meeting to satisfaction.

After a solid sitting and parting with several at our friend John Pickering`'s,
on the 21st of this month,
we went on board a vessel bound to the Island called St. Thomas`'s,
belonging to the Dutch, accompanied by our said dear friend, and Thomas Humphreys,
Jonas Lake, and Joseph Ryan, and on the 22nd landed there,
and understood that the captain of the ship, bound for Amsterdam,
in which we were to take our passage, in order to get to England, was very ill.
We lodged at John Demane`'s one night, and the next day went on board the vessel,
where we stayed mostly till the last day of the month,
and our dear friends above-mentioned, after seeing us placed in the ship,
parted with us in a tender, loving manner,
and my heart was affected in parting with them.
In the time we lay at anchor, the captain died, and the chief mate, Robert Stewart,
was appointed captain in his stead,
who was very kind to us in the many distresses we met with on our passage.

Some days before we sailed, my companion was taken sick, which so increased,
that on the passage he seemed near unto death,
which was a great trial and exercise to me, being myself weakly and feeble,
for we were companions in tribulation; but through the mercy of the Almighty,
he recovered.

After we had been three weeks and some days at sea, a great storm arose,
which appeared to be very dangerous, so that in order to lighten the vessel,
the seamen threw out several weighty things.
After some weeks we got into soundings in the English channel,
and were in hopes to be soon safe landed at some port in England;
but another storm arose, which drove us off to sea.
In eight days we again got soundings, but the wind being against us,
we could not get forward to our expectation, and it rather suiting us to go to Ireland,
the captain altered his course for Kinsale harbour, as the vessel needed repairs.
One of the rudder-irons being broken, made it difficult to steer the vessel;
but by endeavours, they managed pretty well, and the day we made sail for that land,
we got in sight of the harbour; but night coming on,
and being fearful of rocks and shoals, they put off to sea.
The weather being moderate the forepart of the night,
the seamen were too careless and did not keep so strict a watch as they ought;
but the captain, as he lay in his cabin, had so great an uneasiness on his mind,
that he could not lay still any longer, and went towards the head of the vessel,
and found that instead of being out at sea, we were near striking on the land;
whereupon he immediately awaked the sailors, and they tacked the vessel about,
and were very watchful until the morning; thus we escaped that danger.

In the morning it was very foggy; a storm arose, and we could not discover the harbour,
but we were driven about for a considerable time.
They threw overboard one anchor; but the storm continuing and the weather distressing,
we were driven towards the land, and the seamen being almost wearied out,
apprehended we could not keep off much longer.
We were in great distress, expecting the vessel would be wrecked,
and the captain being much surprised, came to my companion and me,
telling us he would do what he could to save our lives,
for that we were in great danger of being lost.
He expected we should be driven on the shore in the night,
if we kept off through the day, and was desirous to know our minds,
what he had best to do; whether to run the ship aground while we had day light,
that if any of our lives were spared, we could the better see how to help ourselves.
We not knowing what to advise him for the best,
only to trust in the good providence of God,
the captain concluded to steer towards the land.
The cries and lamentations of the people were great for mercy to their souls,
apprehending the vessel might be soon dashed to pieces,
and we might suddenly lose our lives.
But I had reason to believe that the gracious and
merciful Being was pleased to hear our cries,
for the nearer we came to the land the fog cleared away, and they espied a vessel,
which as we approached,
we discovered was laying at anchor at the mouth of Kinsale harbour,
where we wanted to be, and as we came on our way, the harbour appeared plain.
Thus through the great deliverance of the Almighty, we arrived there safe,
and dropped anchor.
For this his merciful preservation,
our hearts had great cause to be humbly bowed before him, and the captain came to me,
saying, "`Now if you have it in your heart to return God thanks,
I will join with you on my bare knees,`" and "`if it had not been for your prayers,
we should all have been lost.`"
But I ascribed this great deliverance to the kind mercy of Divine Providence to us all;
although I can truly say,
my soul was earnest in supplication before the Lord at times on this trying passage.

At one particular season, as I lay in my cabin,
not knowing but that we might be swallowed up in the mighty ocean,
the spirit of prayer came on me,
and I was raised on my knees to make intercession with the All-powerful Being;
after which I went upon the deck, and the captain seeing me,
expressed in a very loving manner his unity and satisfaction,
and I thought that the same good power and presence which attended my mind,
had some reach upon his heart.

Oh! in this trying passage, how often did my soul go down into many discouragements,
but I was helped through all, to rely on God`'s mercy;
and one time I took the blessed Bible into my hands,
and it was as if my eyes were cast on that passage in the prophet Isaiah 44:1-3,
where it is said; "`Now hear, O Jacob my servant, and Israel whom I have chosen:
Thus says the Lord that made you, and formed you from the womb, which will help you;
Fear not, O Jacob my servant, and you, Jesurun, whom I have chosen;
For I will pour water upon him that is thirsty, and floods upon the dry ground:
I will pour my spirit upon your seed, and my blessing upon your offspring.`"
This gracious blessing of the Lord to his servants and chosen ones, was a comfort to me,
and in his great condescension he fulfilled his promise to help in the needful time.
