== Chapter III

[.chapter-synopsis]
* Landing at Kinsale in Ireland
* His travels and labours in that kingdom
* His travels in England and Scotland, to the time of returning home

It was on the 24th day of the first month, 1749, in the evening,
that we came to an anchor in this safe harbour of Kinsale.
The officers and people from the town came on board to see what we had in our vessel,
some of whom stayed all night;
my companion and I were confined to the hearing of their noisy conversation,
until the next morning, so that we got but little rest,
and had very little for several nights and days before.
The captain being gone on shore, returned the next day, and a civil man with him,
who mentioned the names of several Friends that had visited that town,
some of whom had come from America, which was pleasing to me to hear of;
they having left their home a little before me,
and had been travelling in the service of Truth.

When this friendly man returned on shore, we went with him to his house, being an inn,
where we were civilly entertained; he took care of our chests and clothing,
and provided us with horses, and a guide to conduct us to Cork, being about ten miles.
When we got there, being strangers, we were at a loss to find out Friends;
we alighted at a public-house, and went in and got some refreshment.
My companion inquired of a man in the house after our Friends in the town, who answered,
that there were a great many of the brethren lived there;
he was desired to go to one of them, and inform him that we wanted to speak with him.

In a short time he brought one of our friends, named Richard Allen,
at the sight of whom I was well pleased, and he lovingly took us to his house,
where soon after came Abraham Fuller, and another Friend, who asked for our certificates,
which they read and were satisfied.
Our friend Abraham Fuller inviting us to his house, we went with him,
and made it our home, while I stayed in Cork.
We were favoured that evening with the company of several Friends,
which I esteemed a great mercy from the Lord,
that after being delivered from so many imminent dangers,
we could be with so kind a people as they were to us.
The next day being the first of the week,
I was at two meetings with Friends in that city, and my companion at one of them,
which I hope will be remembered by both of us.

Being brought unexpectedly and providentially to this land,
I much desired that I might proceed aright in the course of my religious service,
for when on our passage, I expected to land in England.
Meeting with many deep sufferings and trials of my faith, in the West India islands,
as also at sea,
I was ready to fear whether my present undertaking was from a right motion,
or required of me to engage in, thinking that if I got safe to England,
and saw some Friends there, and could meet with an opportunity to return home,
whether I had not best so to do, not knowing that my lot would be cast in Ireland.
But, Divine Wisdom ordering everything that is consistent with his will for the best,
I was made willing to visit Friends of this nation.
From Cork, I went to Bandon with my companion, where we had a large comfortable meeting,
being many people there besides those of our religious Society; then returned to Cork,
where I stayed several meetings.
Leaving my companion in this city, he being desirous to go home from there,
I proceeded on my journey; first I went to Youghall,
and was favoured with a good meeting, after that to Killcommon, and had a meeting;
from there to Cashel meeting, which was pretty large, and I hope to satisfaction.
I lodged at Solomon Watson`'s, who accompanied me to Clonmel,
where I was at two meetings,
which I hope were of some service to stir up the pure mind in those who attended them.

From this place travelling twenty miles, in a great deal of rain, I reached Waterford,
where my kind friends Isaac Jacobs and his wife, received me in a loving, tender manner,
which was a comfort to me at that time.
For I had been travelling in the deeps both inwardly and outwardly,
being alone as to an outward companion, except the person who was my guide;
looking upon myself as a pilgrim and stranger in a strange land;
but the Almighty helped me, praised be his worthy name.
We had a good meeting at Waterford; from there I went to Ross,
at which meeting the wicked were warned of their wickedness;
the next day I had a meeting at Lambstown,
in which I was favoured with my good Master`'s presence,
and it was to edification and comfort.
From this place I went to Wexford, where the meeting ended to satisfaction;
from there to Joseph Williams`'s and lodged, and to the meeting at Cooladine,
and in the evening had a meeting at the widow Stephens`'s,
both of them being comfortable seasons.

I then went to John Wright`'s, and Henry Herrif`'s, and to Billicane,
having meetings to good satisfaction; after which in company with several Friends,
I went to Dublin, and attended the half-year`'s meeting, which was large,
many choice Friends being there, whom I was glad to see.
The good presence and kindness of our dear Lord being witnessed and enjoyed,
both in the meetings for worship, and the discipline, made it a comfortable time to me,
not having seen such a meeting since I left my native land.
The kindness and friendship that appeared among Friends at this meeting,
I have often remembered with comfort of mind,
and the near unity I felt in my heart to a remnant among them,
tended to the renewing of my strength and willingness
to visit Friends generally in that nation.
My journey being laid out by Friends, that I might proceed for the best,
in respect to travelling, I went from my kind landlord`'s, Peter Judd,
several miles to a meeting, and to Killconnor, and was at a meeting there,
which although they were hard suffering times,
I hope were of some service to the solid minded.

I had here a tendering time in the family of Samuel Watson;
his dear wife having visited America, I had seen her in my native land;
she was a worthy and serviceable instrument in the Lord`'s
hand to many I believe where her lot was cast.
Hence I went to Carlow, where the meeting was to me laborious; then to John Lake`'s,
Ballitore, Athlone, and Mountmellick,
some of which meetings were comfortable satisfactory seasons.
At Mountmellick, I lodged at Joshua Strangman`'s,
with whom I had great nearness in spirit,
and thought him to be a hopeful young man in the way of Truth,
and my soul possessed sweet peace under his roof.

I went to Ballinakill, Mountrath, Munderhead, and Rosegay, and had meetings;
some of them being large and edifying seasons,
gave relief to the deep travail of my soul among them, the blessed power of Truth,
which is the crown of our religious meetings,
tenderly affecting our hearts before the Lord.
I then went to Limerick, and was at their meeting in the morning and afternoon,
to satisfaction; from there to Jonathan Barnes, and was at a meeting at Killcommon-moor,
the forepart of which was to me a time of great leanness and poverty of spirit,
but before it ended, was I believe a time of tender visitation to the people;
and I was enabled through Divine help, to declare the Word of life among them.
I went from there to Burr, and was at a solid broken meeting,
which was a comfortable season; then to William Litfall`'s and Ballymorin,
and had meetings; so returned to Athlone, called the centre of Ireland,
and lodged at William Sproul`'s, an ancient loving Friend, who not only appeared to be,
but I believe really was, an example in the way of Truth in that place,
and had a lasting remembrance in my mind.
From there I went to the Moat, and Old Castle;
at the last place there came to the meeting a priest, and a pretty many people,
who behaved soberly, and I hope it was a good meeting.
The next meeting was Ballahays, which was small,
and the comers to it seemed to be but indifferent professors of the Truth,
which was cause of sorrow to my heart; but having cleared myself,
I proceeded to Coothill, and had a meeting, to which several came and behaved soberly;
the next was Cashelshane, which was to satisfaction and comfort; then to Charlemont,
which was a large meeting, and I had hard labour to discharge my duty among them.
Here came a man and woman, who had been troublesome to Friends,
in offering their intentions of marriage.
They could not have unity with their proceedings,
he not being a member of our religious Society, and a disorderly person,
but at the conclusion of the meeting, they took each other as man and wife,
which imposition occasioned the meeting to break up in disorder.

From hence I went to Ballyhagan, which was a large and edifying meeting,
and so to Colerain, Ballynacre, the Grange, and Antrim, and had meetings,
which were mostly hard suffering times.
Several who came to those meetings, I was afraid,
were but lifeless professors of religion.
I had the next meeting at Hilsborough, at which were many Friends,
and it tended to satisfaction; the same day I had a good meeting at Lisburn.
I passed through Belfast to Newtown, where came some who behaved rudely,
and the meeting was not so well as could be desired; the next was Ballenederry,
which was very large, and the Lord`'s good presence being with us,
the hearts of the faithful for his many mercies,
had cause to give thanksgivings and praises to his most worthy name.
After this meeting I had a near parting time at John Murrows, with many dear Friends,
who came to take their leave of me.
I went to Monallin and Lurgan, and had meetings;
to that at the last place came many persons of great note,
and behaved extraordinarily sober, and we were favoured with a good meeting;
the next was at Rafer-Island, to which also came some not of our Society,
who confessed to the truth of what I had to declare among them,
and parted with me in love.
I went several miles that afternoon, and lodged at Dundalk at an inn;
the next day and part of the night I travelled forty miles,
some of the way in a great deal of pain, and in a wet tired condition to Edenderry,
where I was received at John Pim`'s, in a loving, kind manner.
I attended their meetings on the first-day in the forenoon and afternoon,
which were large and I hope in the main, good meetings; the next were at Rathangen,
and Timahoe, which were comfortable.
From there I went to Dublin, and lodged at my dear friend Peter Judd`'s,
and was in and about Dublin nine days, and at,
several good living meetings among Friends in that city.
There was a remnant of dear Friends in some parts of that nation,
whom I had comfort of mind in going to see, and visit in the love of God.
It having been his blessed will to cast my lot in that part of the world,
I laboured faithfully to discharge my duty in his fear, both to Friends and other people,
who had freedom to come to our religious meetings,
and several appeared to be reached by the power of Truth,
who did not make profession among us.

On the 29th of the fourth month, I embarked for England,
accompanied by several Friends on board the vessel, where we parted in tender love,
and on the first-day of the fifth month, I landed at Whitehaven, altogether a stranger,
and no outward companion, which to me was lonely in a strange land.
But the Almighty in his mercy and goodness was near to me, to be my comforter,
and I had great cause to bow with a bended heart in deep thankfulness before him,
for his wonderful providence and many helps and deliverances.
I enquired the way to Daniel Stephenson`'s, by whom I was lovingly received,
and kindly entertained; the next day being the first-day of the week,
I was at two meetings with Friends at Whitehaven, which I have often remembered.
My way being laid out to visit Friends in Cumberland,
I went forward the 3rd of the fifth month towards Cockermouth,
and in travelling on the road my mind was much thoughtful,
not knowing that I should meet with anyone to be a comfort to me;
when not far from the town to which I was going, I met two Friends.
At first sight I did not know either of them, but one of them speaking to me,
I found it to be Christopher Wilson; at which my heart was much rejoiced,
he being a Friend who had travelled among us in the work of the ministry in America,
and I had seen in Philadelphia, The meeting to which I intended,
not being held till the next day, I turned back with him to his house;
where we had near conversation together in the love of Truth.
Next day he accompanied me to the meeting appointed, which was a solid time;
the day following I went to Izel, and had a meeting with the few Friends there,
and although small it was a solid meeting; after that, I was at Pardsaw-Hall,
which was a good meeting, so to Broughton,
and had comfort of mind among Friend thereaway.

I then returned to Pardsaw-Hall again,
and on the first-day of the week the meeting was very large,
and the good presence of God attending the same, made it a humbling comfortable season;
the same day I was at a large meeting, near Christopher Wilson`'s, which ended well;
from there was at Keswick, though small, a good meeting,
so to Mosdale and had a large satisfactory meeting, also at Colbeck, Bolton and Wigton,
some of which were large, and I hope tended to edification and comfort.
I then went to Allanby, and Holm, and had large meetings,
in which the power of Truth prevailed in a good degree; the next was at Kirk bride,
in which I had hard service,
and a close testimony to the unconcerned in the way of Truth,
which I left to their consideration.
I went to Jonathan Astell`'s, who and his wife were choice ancient Friends;
my stay at their house, and being with such dear Friends,
afforded me at that time renewed comfort of mind.
For although the Lord was gracious, powerfully to assist my poor spirit,
in some places to discharge my duty,
yet at times I met with close sufferings and bemoanings,
for the arising of the Divine spring of life, both in myself and others.
I went to Carlisle from there, and so back to Moor-House meeting, then to Scotby,
Kirklington, and a meeting that John Irwen and his wife belonged to,
who were both ancient Friends,
and I believe had been of service in the work of the ministry.
Although some of those meetings were trying times, and attended with hard labour,
I trust that I was clear in the sight of God in endeavouring
to be faithful to what I apprehended to be my duty.

From Cumberland I went into Northumberland, and the first meeting I was at,
was Cuthbert Wigham`'s, where was a considerable number of newly convinced Friends,
which was a comfortable and contrited meeting before the Lord;
from there I went to West-Allandale, to a large meeting,
which was powerfully reached with the sense of the love of God.

The next meeting was at Alston-moor, which though not very large,
I hope might tend to the benefit of some; then to Penrith, Terril,
and Strickland meetings, some of which were to satisfaction,
and I met with a kind reception,
and had near unity with many dear Friends in several places.

From Strickland, I went to Kendal, in Westmoreland, to my dear friend John Crowdson`'s,
where I stayed some days and rested as to travelling;
but attended pretty many meetings in Kendal, to which belonged many worthy Friends,
who were extraordinarily kind and friendly, which I esteemed a favour.
At that time, I was in a very low situation of mind,
much overwhelmed with many inward sorrows, and conflicts of soul;
but was intent to do the best I could to get through what might
fall to my lot at so great a distance from my outward habitation,
trusting in the Almighty hand of the Lord, who alone knew my distressed condition,
and to whom I put forth my cries and secret addresses for relief;
dominion and everlasting praise be rendered to him forevermore!
In the course of what he was pleased to lay upon
my mind to say in meetings by way of testimony,
he was also pleased to be gracious in appearing to
open my way in the cause I had at heart,
which was the promotion of well-doing, and the good of mankind here and hereafter;
at this place meetings were large, and I hope blessed with the notice of heaven.
To this meeting belonged Margaret Coupland, who had visited our parts,
was an exemplary solid Friend, and retained the lively sense of truth.

While I was here, I received a letter from my kind friend Israel Pemberton the younger,
giving me some account of my dear children and friends at home,
which was very acceptable to me.
This dear friend`'s worthy father being a bright
pattern and elder in the church of Christ,
given to hospitality and good works;
the near unity I had with him in spirit gave me much comfort and satisfaction of mind,
as he was brought frequently to my remembrance in this journey.
On account of my children, I had been often concerned,
and dropped many tears for their everlasting welfare, they being very near to my life.
Oh, how I much desired that they might choose the Lord for their portion,
the God of Jacob,
and his blessing for the lot of their inheritance! then I trusted that he would
be pleased to be a sure friend to them as they kept in his holy fear and counsel.

From Kendal I went to Grayrig, which was a solid tender broken meeting,
also to Preston Patrick, Windermere, and Hawkside, which meetings were to satisfaction,
and ended well; then to Hight meeting, in Lancashire,
which afforded some comfort to my mind.
The next was at Swarthrnoor-hall, where George Fox belonged in his time,
which was a large and a good meeting; from there I went to Lancaster,
and was at two meetings on the first-day of the week, which were large and comfortable.
Here lived Lydia Lancaster, and Elizabeth Rawlinson, both worthy Friends,
who had visited America; and in one of those meetings,
they both appeared in a living testimony for the Lord in their advanced age,
and it did me good to perceive that they were alive in the root of life;
at this meeting was William Thomas, a ministering Friend lately landed from Tortola,
I went that day home with William Backhouse,
a Friend who had visited America in the work of the ministry;
he received me very kindly and lovingly in his house.
The next day I was at Yellan meeting, which was to satisfaction; then to Bentham,
which was a large meeting, and attended with the solid power of truth;
from there to Dent, in which meeting the spring of life was opened among us,
to the comfort of the sincere in heart.
To this meeting belonged John Burton, who had visited our parts;
a dear Friend I was glad to see, having seen him in my native land.
The next meetings were Brigflats, and Ravenstondale, which I hope tended to edification;
to the last belonged Alice Alderson, a worthy instrument,
who had travelled in America on the Lord`'s errand,
and was truly acceptable in her religious visit.

I went to Grisedale, and was at a large living meeting; the next was at Counterset,
which was large and solid; then to Swale-dale, Ausgarth, Richmond,
and another meeting in my way to Raby, some of which were satisfactory solid seasons.
At Raby, I met with several worthy Friends,
who I found in conduct to be true helpmates to me,
particularly James Wilson and Joseph Taylor; I had seen Joseph in Philadelphia,
when on his religious visit to our country,
and it was a pleasure and comfort now to see him in his own habitation.
From this place, I went to Bishop-Auckland, Durham, Benfieldside,
and New-Castle upon Tyne,
which meetings were mostly hard laborious times to my baptized spirit; then to Shields,
Sunderland, Shotton, and Darlington, the opportunities, with Friends thereaway,
being mostly comfortable; after these meetings I went to Stockton, Gisborough, Yalton,
and Castletown, where I had meetings, some of which were to satisfaction.

I went to that dear ancient Friend John Richardson`'s,
who had been twice to America on religious visits,
and had taken much pains in his day and time,
for the spreading and promoting the gospel of peace and salvation in the earth.
Although he was ancient and feeble in body,
he was fresh and green in the life of religion, and my heart was refreshed,
in the unity and fellowship of divine life, in being in his company.
I lodged here, and the next day went to the meeting at Kirby-moor-side,
to which he belonged, which was a solid good meeting; from hence to Ampwelford,
Rilsdale Thirsk and Kirby, some of which were weighty solid meetings,
and the humble in heart were contrited therein; then to the quarterly meeting at York,
which held several days for worship and the discipline of the church.
It was very large and attended by many solid Friends from their particular meetings,
near unity and gospel fellowship being in a good degree manifested;
this opportunity begat an agreeable acquaintance with many Friends
whom I afterwards found to be very friendly and kind to me,
as I went forward on my journey.
From this city I went to Thornton, Molton, Pickering, Whitby, Stanton, Scarborough,
and was at meetings, several of them being large, and edifying.

I was next at Bridlington, to which meeting came a pretty many people,
but it was a time of hard labour,
the meeting being declined from what it had been formerly,
according to the account I had of it; and the few Friends left,
did not live in that unity I could have been glad to have found among them.
To this meeting once belonged Margaret Langdale, who came to Philadelphia,
and was afterwards the wife of our worthy Friend Samuel Preston, late of that city;
her labours among Friends in the work of the ministry were of great service in her time.

From Bridlington I came to Hornsey, and to two other places, and so to Hull,
having meetings, some of which were large,
being attended both by Friends and other people,
and the Divine presence of the Almighty being over all, they ended to good satisfaction.
From Hull I went to a meeting in my way to Cave-holden, Pontefract, Rawcliff, and Thorn;
to which meetings I travelled in great affliction of body, and much conflict of spirit,
on account of great besetments that fell to my lot in the course of my travels,
and the work and warfare that I honestly laboured in,
having left all that was near and dear to me as a creature,
on account of the blessed Truth; that had not the All-powerful aid helped me,
to look to him in whom everlasting strength is, I had fainted;
but dominion and praise to him forever,
his strength was made perfect in my great weakness.
And in those meetings I was enabled to bear a testimony to his Almighty name,
although out of meetings greatly beset; yet keeping my confidence in God,
he was pleased in his great mercy to cast up a way for my help and deliverance!

From Thorn, I went to my dear friend Joseph Atkinson`'s at Rawcliff,
who and his wife were as tender towards me as if I had been one of their own family;
after some stay with these my loving friends, I got better in health,
and the motion of life and love increasing in my heart to visit the churches,
I proceeded, and went to Thorn meeting, which was an edifying good time.
Here I met with my friend John Fisher, who accompanied me to several places,
having before travelled mostly alone, both in England and Ireland,
as to a constant companion.
We had two meetings in our way to William Payne`'s, where we had a meeting;
and at Hansworth-Woodhouse, to which last belonged John Haslam,
a dear Friend who had been very acceptable in his religious visit to Friends in America,
and had visited the churches to the great comfort of the faithful;
his agreeable company at his own house,
renewed our fresh unity in pure and lasting fellowship in the gospel of peace.
From there we went to Sheffield, where we had two large good meetings;
the next was Burton, which was large and a comfortable time;
the next meeting was at Wakefield, where came a pretty many people,
in which I was silent, as it so fell out at several places in meetings appointed,
which I have concluded, if rightly minded,
might be a means to bring people to hearken to the alone teacher in their own hearts;
for it is there the Word of faith is to be obeyed.
Although the dependence of the outward ear sometimes may be upon the servants of Christ,
yet they cannot speak aright, and to the witness in the consciences of men,
but as he is pleased by his Spirit to give them utterance;
the design and tendency of all true gospel ministry,
which springs from the Divine Word of life,
being to stir up the pure mind to adhere to the holy
teaching of Christ in their own souls.

The next meeting was at Gildersham, which was a solid good opportunity,
and dearly united my spirit to some who attended the same; from hence I went to Leeds,
and was at two large meetings on the first-day, and at a week-day meeting, some of which,
I hope tended to promote true spiritual worship to God.
We then went to Waldale, Brighouse, and Rawden, and had meetings which were large,
solid and comfortable; the next was at Bradford, to which came a pretty many people,
and it ended well; we lodged at Benjamin Bartlett`'s where we met with Edmund Peckover,
Jane Hoskins, and May Drummond; my worthy Friend Edmund,
having left great sweetness in the minds of many in America, and on mine in particular,
it was a comfort to me to see him again.

From hence we went to Halifax, accompanied by William Longmier,
a dear brother and fellow helper in the gospel,
who had been with us to several meetings before, and was choice company,
and did me much good; the meeting at Halifax was large,
and ended I hope to the honour of Truth.
Here I parted with my companion, John Fisher, and went to five distant places,
having meetings in my way to Skipton, some of which were large,
being attended both by Friends and other people, and I believe to edification.
I had a good time at the meeting at Skipton, and with the scholars,
of my friend David Hall at his school, having near unity with his company.
I lodged here one night, and went from there to Lowtherdale,
where William and Mary Slater belonged,
who were serviceable Friends in the work of the ministry;
this meeting was large and eminently affected with the sense of Divine life and power.

The next meetings were Ayrton, Settle, and Newton,
which were mostly solid and satisfactory; the next was Narsedale, which was small,
and I was fearful they were very cold professors of the right way of worship;
m this I was silent.
I went to the Fiel, Proud-Preston, Longridge, and Elmaridge, and had meetings,
which though mostly small were pretty satisfactory;
the meetings following were Sowledale, Trowden, Marsden, and Trodmarden,
and at another place, which were generally large and edifying.
I went next to the meetings at Hold ham, Manchester, Langtree, Aston, Bickerstaff,
and Liverpool, some of which were pretty large and solidly comfortable;
from Liverpool I went to Penketh, Warrington, and Framby,
which meetings were large and uniting seasons to the honest-hearted;
at the last place I was much relieved and set at liberty
through the dominion of the Divine power that attended.
From this place came Esther Clare to Pennsylvania, a Friend of the ministry,
a member of our meeting in Philadelphia,
who was divinely endowed and inspired with a knowledge in the things of God`'s kingdom,
and was a helpful instrument in the hand of the Lord to me in my young years.

The next meetings were Sutton, Newton, and John Downs in Cheshire, to solid comfort;
from there I went to Chester, and to Rixham in Wales, which were hard small meetings,
and dull as to the life of religion.
Returning into Cheshire, to Namptwich, and Middlewich,
I had meetings which were comfortable seasons;
and then went to the house of a Friend belonging to Morley,
where I rested some days as to travelling.
During my stay here I visited the sick, and some Friends`' families,
and Morley meeting which was large, and the good presence of the Lord attending,
made it a good meeting; from there I went to Stockport, Maxfield, and Leek,
some of which meetings were large and to satisfaction;
the last place was in Staffordshire.
In my way from Joshua Toft`'s to Stafford I had a meeting; as likewise in that town,
which was small, and the life of Truth appearing at a low ebb among them,
was cause of sorrow and suffering to my mind; the next meeting was at Birmingham,
which was pretty large, and I hope of service to some who were there.

Then I went to Coventry, and lodged at my kinsman`'s John Newman,
his wife being my wife`'s first cousin; they were exemplary Friends,
truly kind and loving, and a comfort to me in meeting with them at their own house.
Here I heard of the death of my dear aunt Martha Chalkley,
from a friend living at this place;
the account of which much affected my spirit for
the loss of so near a relation and dear friend,
whom I much loved and esteemed, she being one who feared the Lord,
and was serviceable to Friends where she lived in her time.

At Coventry I was at two large meetings,
one of which was much crowded by reason of a funeral,
and both were solid opportunities with the people; went to Badgley,
and another place some distance, and was at two solid meetings; the next were at Warwick,
and Eatington, from which I went to Shipton, in Worcestershire,
and was at two large meetings to edification; from there to Longcompton, Radway,
and Harborough, some of which meetings were large and solid.
At the last place I was told, that the people when they heard of the meeting intended,
said they would come to see the outlandish man, and many came who behaved soberly,
and Divine life prevailed that day among us to the comfort of my mind.
I went forward to two meetings in my way to Worcester, at distant places;
at Worcester the meetings were large '`and solid,
and though some professors appeared to be gone out from the way of the self-denying life,
into much liberty and extravagance,
yet I believe it was a time of visitation to their souls.
From this city I went to Bewdley, Bromsgrove, Stourbridge, Dudley, and Coalbrookdale,
at which places I had meetings, mostly pretty large, solid, and edifying;
the next place I went to was Shrewsbury, where, in company with several Friends,
I visited two dear Friends who were in prison on account of tithes;
our hearts being tendered together, we had to praise the Lord, and were comforted,
although in such a place of outward confinement;
I was also at a meeting in the meetinghouse which though not large, was I hope well.

From hence I went into Wales, with John Fowler, a solid young man,
who though not a public minister, came out of Warwickshire on purpose to accompany me.
Our first meeting was at Dolobran in Montgomeryshire, which was small and poor;
then we came to Ellis Lewis`'s where we had a meeting with a few plain kind Friends,
and at Twinde, in Merrionethshire, where were only three Friends to keep up the meeting;
but it afforded much comfort to my mind, that I had an opportunity to see them,
with whom we had a solid time.

The next meeting was at John Goodwin`'s in the same county, a brave worthy man,
who had been instrumental to bring several to the knowledge of the Truth thereaway,
and where is a large meeting, in which it gave me satisfaction in being among them;
from there we went to Talcot, and so into Radnorshire in South Wales,
where we had two large good meetings; then to Pennybank in Carmarthenshire,
and at Thomas Price`'s we had a small solid meeting,
and at Ann Evans`'s in Cardiganshire, to which came many people,
and the meeting was to satisfaction and comfort.
We then had a meeting in our way to Carmarthen, and there also,
which were small and but few faithful labourers,
and the unsteadiness of some made it a mournful time to me;
from there I came to Haverford-west, where the Friends of Redstone met,
which meeting was somewhat satisfactory.

In my way from my dear friend John Lewis`'s to Swanzey, I had two distant meetings,
one of which was large and mostly of people who did not profess with us,
and I hope was of good service;
the life and power of the Divine word bringing the minds of the people into stillness,
the meeting ended well.
I was at two meetings at Swanzey, the first small and silent,
the other a large open time; we then came to John Bevan`'s,
where we had a small hard meeting, then at Pontypool,
where the meeting was pretty large and I hope ended well;
we had also an evening meeting at a Friend`'s house, which was a comfortable time;
and one at Shire Newton, not very large, but a good meeting,
this being the last in Wales.
Having visited all the meetings in that country, that could be called by our name,
as near as I remember, except Pedstown, and some of that meeting were at Haverford-west;
when I had got there, I had great cause to be humbly thankful to my kind Lord and Master,
for his Divine help and merciful preservation through
much toilsome travail both of body and spirit.

From there I went to Ross, in Herefordshire,
and on my way parted with my companion John Fowler,
his desire being to return home after this journey.
At Ross I had a comfortable meeting, and went forward to Hamler, Leominster,
and Bromyard, having meetings; the two first were solid good opportunities;
at Leominster, it was large and some hopeful newly convinced Friends were there;
the other was almost lifeless as to a true zeal for Divine worship,
and but little prospect of the growth of Truth.
I came into Gloucestershire, and had meetings at Tewkesbury, Cheltenham, Gloucester,
Painswick, and Nailsworth, some of which were hard suffering times;
I sincerely wish the life of righteousness more abounded among the professors thereof.
Then I came to Thornbury and to Ann Young`'s, and was at two good meetings;
then to Bristol, where I attended several large meetings,
in which the kind hand of the Lord was with us,
and I found Friends there to be very loving, and left them in the same.
I also visited Kingsweston and Frenchay, which were large, solid and edifying meetings;
from there to Sadsbury, Tedbury, Cirencester, Addington, and Camden, having meetings,
and I trust was clear as to my duty among them; the next meetings were Milton, Burford,
Whitney, Chalbury, Chippingnorton, Hooknorton, and Sedford,
several of which were large good opportunities.
I then went forward to South Newton, and Banbury, and was at three meetings,
one of which was silent, the other large good opportunities.
At Banbury I was favoured with the company of my friend Benjamin Kidd,
whom I had formerly seen in Philadelphia, when a lad,
and was a comfort to me when I was in a reverent search after the things of God`'s kingdom;
the friendship of this dear friend at his house,
was also now an encouragement to me in the way of my religious service.

From hence I went forward into several counties,
and was at a number of meetings in different places,
which I hope were of profit to the people,
and in some places they were large at two of them I had the company
of my beloved friends Catherine Payton and Rachel Wilson,
they being on their way to the yearly meeting at London.
We went forward together to Reading,
where I met with my dear worthy friend Samuel Hopwood, with whom when in Pennsylvania,
I had travelled to some places,
and I believe was now glad of our meeting to see each other again;
he was a zealous and fervent labourer in the Lord`'s vineyard,
who I believe had blessed his labours to many souls;
we had a meeting at Reading to sweet satisfaction.
From there we all went to Maidenhead, and were at a meeting there, in which I was silent;
from this town we went to London together, and on our way several Friends met us;
our friend John Hunt being one of them, would have me to his house,
and gave me a kind reception,
where I made my home for the most part during the
times my lot was cast in that great city.
The yearly meeting was large,
and I hope edifying to many honest travellers in Zion`'s way.

When this meeting was over, I went for Scotland,
finding my mind drawn forth in much love to Friends in those parts,
as I had after I first landed in England; but through some discouragement in myself,
omitted the opportunity of going there when I was in Cumberland, near the borders of it,
which caused me much more travelling to get to see Friends thereaway;
but regarding peace of mind, which is to be valued above all the world,
I now gave up to perform this visit.

From London, I went through several counties,
having many meetings in particular places appointed.
I was also at three yearly meetings in my journey, Colchester, Woodbridge, and Norwich,
several of which were large and satisfactory;
as were also some of the appointed meetings, though small;
and I had near communion in spirit with some Friends as I passed through Essex, Norfolk,
Suffolk, and Lincolnshire, and in Yorkshire.
I proceeded from York to Darlington with my companion John Kendal,
a solid young man of Colchester, who had a savoury testimony for Truth;
we had a good meeting at Darlington, then went forward to Durham, and Newcastle,
at each of which towns we had meetings,
and Friends were kind in assisting to get us on our way to Alnwick,
where we had a small meeting,
and lodged at John Doubleday`'s. Woe then proceeded to Kelso,
where we had two good solid meetings; then to Edinburgh,
and had a meeting to some satisfaction; after which we had but one little meeting,
which was in a Friend`'s house, until we got to Aberdeen,
where we had two that were large,
in which I hope the Lord`'s power was in dominion to solid comfort.
From there we went to Kinswells, Inverary, and Old Meld rum,
and had meetings to some degree of satisfaction;
the last named place was the furthest meeting we had in Scotland, which was pretty large.
We came to Kilmuck, and were favoured with a comfortable meeting and somewhat large;
the next was at New Aberdeen, also at Urie, at the seat of Robert Barclay,
which where solid opportunities.
At Urie, there came many people, Friends and others, who behaved with solid attention,
which made it a time of profit I hope to some.

At this place we met with our friends David Barclay,
his wife and two daughters from London,
who had come on a visit to their relations and friends in those parts,
and when they set out from home we came a pretty many miles on our way with them.
They were very kind and friendly, and by this acquaintance,
such a love was begotten in the hearts of those kind friends,
that when I came back to London they had me several times to their house,
and were truly respectful to me.
Parting with them in Scotland, we went towards Glasgow,
and had a small good meeting some miles distance from there,
and in Glasgow we were at three meetings, two of which were large,
and in the main to solid satisfaction.
After we had visited all the meetings of Friends in these parts, as near as I remember,
except one, some of the members of which were at the meeting at Urie,
we came on our way to England again,
which was several days journey before we got to Carlisle,
and were obliged to lodge at several inns, which was not quite agreeable;
but when I got over the water which parts England and the other land,
my heart was tendered and broken before the Lord,
under a sense of pure peace for the performance of this visit to that part of the world.
I thought there were a few solid Friends in places,
and could rejoice to hear that their number was increased.
We went through Carlisle a short distance,
and lodged at our kind friend Richard Wait`'s at Newtown; next day we set out for Kendal,
and got there that night, where we were lovingly received; stayed some time for rest,
and attended several large, solid, good meetings,
and visited several dear friends in the town.

From hence proceeded to meetings at the following places, namely, Crook, Preston,
Lancaster and Manchester, which were mostly to satisfaction; then went into Derbyshire,
to Monyash, Matlock, Brick and Chesterfield, and several other places,
some of which meetings were large, and I hope of service through Divine help,
for the promotion of Truth.
I parted with my dear friend John Kendal, soon after I left Manchester,
he intending to return home, after our long journey through Scotland.

From this county I passed through Northamptonshire, Lincolnshire, and Leicestershire,
having many meetings, several of which I hope were to the satisfaction of the faithful.
At a particular meeting not far from Leicester,
to which came a considerable number of Friends,
some of them from several distant meetings, it being the first-day of the week,
as we sat together in silence before the Lord, there was a shock of an earthquake,
which made a great stir in the place;
the people who were met at another house for worship, came away, as I was told,
to our meeting,
where we were preserved in great stillness and little appearance of slavish fear,
and I hope it was a time of singular benefit to that assembly.

From this county I went into Rutlandshire, Buckinghamshire, Bedfordshire,
and Hertfordshire, and was at a number of meetings,
some of which were favoured with a sense of the Lord`'s blessed power and presence.
The next counties were Huntingdonshire and Cambridgeshire,
in which were several solid meetings, though that at Cambridge was small,
and the darkness of that dark place much depressed my spirit,
which was attended with deep suffering.
I went from this county into the Isle-of-Ely,
and visited the meetings generally thereaway;
in the performance of which I had some comfort of mind; from hence I went into Norfolk,
Suffolk, Essex and Hertford counties, visiting meetings as they were laid out by Friends,
there being in several places some valuable solid brethren,
with whom I had near unity of spirit,
in that faith which stands not in the wisdom of man, but in the power of God.

I came into Middlesex, and had meetings also at Basingstoke, Alton and Salisbury,
and several other places in Wiltshire,
some of which were comfortable seasons in the best sense; I then went into Somersetshire,
and to Bath and Froome, and some other places, and had meetings; then to Posset,
and was favoured with a satisfactory meeting there.

Next day I was taken ill at my friend James Player`'s, it being, I thought,
pretty much the effect of a cold,
hard travelling and a close engagement of body and
spirit I had passed through from one place to another.
This illness detained me some weeks, in which time I was brought very weak in body,
and at times low in spirit; but through the kind mercy of God, having somewhat recovered,
though still weak, I set out for the West of England, and went to Clareham, Glastonbury,
Bridgewater, and many other places, at which I had meetings,
some being large and mercifully favoured with Divine help, uniting love and power.

After visiting the meetings in the county of Somerset,
I went into Devonshire and Cornwall,
having the company of my dearly beloved friend John Player,
to whose spirit I was nearly united in the love of Truth;
he was a great comfort and help to me in my weak
condition at his uncle`'s. I would just remark,
that in some of the counties in which I have been, some dear young people,
who were libertine in the show of pride and finery of the world, became sober,
solid and exemplary.
One young woman in particular was so reached, as I sat in a Friend`'s house,
though I had nothing by way of testimony in words to her condition;
yet the weight and exercise attending my mind at that time, so reached her understanding,
she became a plain solid Friend, and before I left England,
I heard her in the ministry at a meeting, and as I thought,
to the general satisfaction of Friends present, I was at Exeter meeting in Devonshire,
and had a weighty solid time among Friends there,
although I was much afflicted with the conduct of one professing the Truth,
that pleaded for carnal defence,
and asked what defence we had in the province of Pennsylvania!
I told him that Providence was our defence;
yet he continued to plead for carnal defence in such a manner,
that gave me much pain of mind, and I told him that I had no unity with his principles,
and bore my testimony against his unprofitable discourse.

I went to several meetings in my way to Kingsbridge, where I had a solid meeting;
from there took a number in my way to Austle in Cornwall;
some of which were to satisfaction, and I hope of some service to the right-minded.
After a weighty good meeting at Austle, I came to Falmouth,
and had one in which I hope I was clear as to my duty among them;
then accompanied by my dear friend Samuel Hopwood, I went to Penzance,
and many other meetings in these counties; from this place,
where we had I hope a serviceable meeting, I returned,
taking several meetings in my way to Bridport in Dorsetshire,
We had two meetings in this town, the last of which was large,
the people being told of an Indian, +++[+++to be there]
as I had come from America.
I believe it raised a curiosity there, for a large number came to the meeting,
and as they came in looked on me, and one upon another.
But after a while they behaved in a sober manner,
and my dear Lord and Master favoured the opportunity, I hope to the comfort of many.
When the meeting ended the people departed with quietness and sobriety;
for which I had cause to be truly thankful,
being much concerned how we should fare that day,
so as not to occasion any blame to the good cause
I have sincerely laboured to promote from my youth,
humbly desiring that my endeavours, although weak, might tend to advance the same.

After having a pleasing time, much to my comfort,
with my loving kind friend Samuel Bownas,
who had visited America in the work of the ministry twice,
I proceeded to several meetings in my way to Weymouth and Pool,
where I also had meetings, some of which were solid times.
Taking several in my way to Southampton, I had there a small meeting;
then passed over to Cowes on the Isle-of-Wight, and after visiting Friends there,
and being favoured with some solid meetings among them, I returned to Southampton.
The next was a good meeting, though small, at Portsmouth;
then a satisfactory large meeting at Chichester, and two in my way to Lewes,
where I was at a meeting to which belonged some loving Friends,
I took a meeting in my way to Kent county, and was at several as I went to Dover,
some of which were satisfactory;
though at Dover I had a hard time with the Friends attending the meeting.
Went to Folkstone, and so forward to Canterbury, and had a good meeting;
as also another between this place and London.
At London, I went to my friend John Hunt`'s, my usual lodging;
stayed sometime in this city, and visited many meetings which were large,
and I had good cause to be thankful to God for his eminent power and presence,
being therein manifested to the souls of his people.
I hope several of those meetings tended to the edification
and comfort of the faithful among them;
believing that the Lord has a choice people in that great city,
who fear his great Almighty name,
and they are near to my spirit in the covenant of love and life.

After I had thus visited London,
I went to a considerable number of meetings in places some distance from there,
some of which were large, weighty, solid opportunities; my beloved friend John Pemberton,
whose company was acceptable, being with me at several of them.

Having gone through all the counties in England,
and generally visited Friends meetings therein, as also those in Wales and Scotland,
I attended the yearly meeting in London,
which was large and much favoured with the
lovingkindness and blessed presence of the Almighty;
many dear Friends being here with whom I had near acquaintance,
it was a comfort to my spirit that I could see them
and part with them in the unity and love of Truth.
A short time after the conclusion of this meeting, accompanied by several loving Friends,
I went to Gravesend, in order to embark on board a vessel bound for New York,
which not being ready for sailing when we came there, our dear friends left us,
I believe in true love; my spirit nearly and affectionately parting with them.
Edward Cathrall of Philadelphia, was passenger with me in this vessel.
Chevalier Dean being commander;
we set sail and came away as soon as we could from Gravesend,
and after a passage of about eleven weeks,
landed at New York on the 10th day of the seventh month, 1751, old style,
and on the 13th of the same month we got home to our habitations,
being the day before our yearly meeting in this city.
It was through the great preservation of the Almighty, who was,
and is a God nigh at hand,
who supported and preserved me in great probations and conflicts of soul,
beyond my ability to set forth in words.
I think it my duty to say.
Good is the Lord and worthy to be greatly feared, praised, loved, honoured, worshipped,
and obeyed!
His goodness, mercy and grace have been eminent for my preservation and salvation,
that he would not allow me to be confounded,
although he was pleased to permit great provings to befall me,
both in my passage home and after I got to my habitation,
according to his All-wise purposes;
yet underneath has been his everlasting Arm of compassion and strength,
which has wrought for my deliverance, and enabled me to commit my soul, body,
and spirit to his keeping.

My dear children and affectionate Friends, I believe were glad for my return to them;
and although I much desired to get to my native land and to see them again,
after an absence of more than three years,
yet my expectation as to the pleasure and comfort of that
Divine blessing in a manner I could have wished,
was much disappointed,
which I have thought was in part occasioned through an omission of duty,
though I hope it was not wilful;
it being to go on a visit to a people of another language.
I omitted the opportunity of performing that part of the service;
had I gone on that errand I might have got home as soon as I now did,
and enjoyed my once expected satisfaction.
A vessel belonging to our city, the captain a member of our Society,
whom I knew and esteemed, was desirous of my taking passage with him from London,
from which he did not sail until several weeks after us, and arrived at Philadelphia,
about the time I landed at New York.
Had I proceeded on the visit which was upon my mind,
it was thought I might have performed it, and have been ready to embark in this vessel;
but a cowardice and diffidence of my own abilities at times,
and a fear of going too fast, I think I can honestly say, more than wilful disobedience,
brought some of the greatest sorrows upon me that I have met with in the world;
but the mercies of God are great, who ought to be served and adored,
and is worthy of the deepest reverence that can be ascribed to his all-powerful Name!

After a time of great anxiety he was pleased by his gracious Arm to deliver me,
and to put a new song into my mouth,
even praises to him the living God! the light of
his glorious countenance afresh shining upon me,
his blessed "`Son of Righteousness`" appeared with healing under his wings,
and I was set at liberty again in a good degree to serve and praise him, the Lord,
in the land of the living.
