== Chapter IV

[.chapter-synopsis]
* His visiting meetings in Pennsylvania and New Jersey.
* His fourth journey to New England.
* His visit through the Southern Provinces to South Carolina, etc.

I again took fresh encouragement to do my best endeavours,
both with respect to temporal and spiritual things,
and settled myself with my two children, and my wife`'s mother,
who lived in the same house with us.
I kept to diligence in my outward calling,
wherein I was blessed of the Lord with all the needful
things of this life for me and mine,
and through Divine help,
I was enabled to perform my religious services at home and abroad,
as I was obedient to the blessed ability that God gives,
at times visiting Friends in Pennsylvania and New Jersey,
with whom I had great nearness in the love of the Heavenly Father.
Many of us were renewedly united in that love which brought us near to himself,
and made known unto us the way that leads unto life and peace, as in the beginning.

In the year 1753, having the unity of my dear Friends at home,
my loving friend Isaac Zane being my companion, I went to Long-Island,
and visited all the meetings of Friends there,
and some places where meetings were not usually held, or not very often, at Jamaica,
and several other places.
I found great openness among the people, and some very large meetings,
and I think I may say to the praise of the Lord, I was greatly favoured with his light,
life, and blessed presence,
which nearly affected my heart with gospel fellowship to his children and people thereaway,
and returned in the possession of great satisfaction in my own bosom.

In the year 1754, I went in the unity of Friends,
with my dear friend Israel Pemberton as far as Boston in New England;
and as we went forward were at a comfortable meeting at New York;
from which we went by water to Newport, Rhode-Island,
and arrived there the evening before the yearly meeting,
at which were our friends Catherine Payton from England, and Mary Peisley from Ireland. The
The gathering of people was great and much mixed,
the love of God in Christ was truly preached, and lovingly extended to them,
and I hope it was a good meeting to many.
After it ended I went with my friends Israel Pemberton and Thomas Lightfoot to Boston,
and from there I went as far as Lynn and Salem, and returning to Boston,
there again met my two loving friends,
and had a meeting which ended as well as I expected,
the people attending it behaving soberly.

We then set off for the yearly meeting at Nantucket, and went by water from Woods-Hole,
stopped at an Island in our way, but being detained by contrary winds,
did not reach the meeting so soon as we desired.
We got there before it was over,
and met again with our two women friends before mentioned,
and there being many Friends on this Island,
it was a comfort to me that I had an opportunity of seeing them once more.
I esteem it a mercy from the Divine Being,
for it seemed as I thought a risk of our lives to venture as we
did in a little open boat a great distance from the land;
but the intentions I believe of us all were for one good purpose,
that we might have a time at that meeting with God`'s people to serve him,
more than for any other consideration.
It was a large meeting, and in some degree comfortable and edifying;
and when it was ended, a pretty many of us,
in company with the two European women Friends, took passage and landed at Woods-Hole,
where we had an evening meeting,
I believe to solid advantage and comfort in some good degree.
Thomas Lightfoot concluded to go forward to accompany the women
Friends in their visit to the other parts of New England,
and my friend Israel Pemberton and myself returned to Newport,
where we were at several meetings; one was at the burial of the wife of Samuel Holmes,
and in the main they were solid meetings.
We proceeded homewards through Connecticut, and got to New York, Staten-Island,
and New Jersey, having a large comfortable meeting some distance from Joseph Shotwell`'s;
from which we came pretty directly home through the tender mercies of the Lord;
this journey nearly united our hearts to each other,
and in his goodness he was pleased to afford some degree of peace to my mind.

In the year 1755, I visited most of the meetings in Bucks county,
some of which I had not been at for several years,
and thought were much increased as to the number of young people,
and were large solid good meetings;
wherein I had great nearness of spirit with many tender-hearted dear Friends,
and returned home with sweet peace in the performance of this visit.
I also attended several meetings in this province and New Jersey with
my two worthy Friends Nicholas Davis and Adam Mott from New England,
which were large and I believe serviceable to many,
and I received some pleasure and deliverance to my soul,
after some distressing trials of my faith, and provings of hope towards God,
which I have received as an unspeakable favour from him,
that he was pleased to bring me out of a horrible pit and set my feet on a rock;
that I can thankfully say, "`None is so holy as the Lord,
nor any rock like our God that is in heaven, for the help of his people,
and in his excellency above the skies.`"
After a very acceptable visit to these parts, from those our dear friends,
in returning homewards Nicholas Davis died by the way;
and although the loss I believe to be great to Friends where he belonged,
and those abroad, where his lot was cast on his Lord and Master`'s errand;
yet it is comfortably to be hoped, that he is at rest from his labours,
and received the reward of a faithful servant.
Oh! the sweet savour of life,
and eminent power of the Divine Word that attended this man of God, whose sweet company,
edifying conversation and tender love to the little and lowly lambs of Christ;
(though a threshing instrument in the Lord`'s hand,
against ungodliness and unrighteousness of men,
that hold the truth in unrighteousness,) are not
to be forgotten by those left behind while in mutability,
who have had the benefit of his gospel labours and rightly esteem them.

I also accompanied our dear friend Catherine Payton, with several friends of our city, to
to visit the families of many of our fellow members,
which service I think it may be thankfully said the Lord owned,
the states and conditions of the people being suitably spoken to.

In the year 1756, I visited several meetings in New Jersey, as Mount Holly, Burlington,
Old Springfield, Mansfield, Crosswicks, Bordentown, and Upper Springfield,
which were generally large, and livingly attended with solid comfort;
also with my dear companion Isaac Zane,
I had several satisfactory seasons in some families,
where we went to visit several ancient Friends, also at the houses where we lodged.
After these opportunities we went for Little Egg Harbour,
stopping at a saw-mill on the road, called Mount Misery, where they desired a meeting,
and finding freedom in my mind, we had a tender time with the people,
though a desolate place.
We had two meetings at Little Egg Harbour,
and I found my mind nearly united to some worthy Friends of that place;
from there we passed over a great marsh and a river to Great Egg Harbour,
where we attended a meeting at each meetinghouse,
and it was cause of gladness to see an increase of tender-minded Friends thereaway.
Not having been there for many years,
there appeared a revival of love for Truth and zeal for the same;
since my being last there they had built a meeting-house,
in which we had a powerful satisfactory meeting.
We crossed the river to Cape-May, and had a meeting at the widow Townsend`'s,
and one in the evening at her son`'s,
and from there we came to Greenwich and Alloways creek, having a meeting at each place,
where came a pretty many people, and it was to some degree of comfort.
After the last meeting we reached home, though it was somewhat late in the night;
and although some part of this journey was attended with
much riding and fervent labour in the Lord`'s work,
I had cause to be thankful that I was obedient,
and that he was pleased to enable me to perform my duty.

In this year, and in 1757 and 1758, I attended the Indian treaties,
some part of them with several dear Friends of our city, at Easton in Northampton county,
at the time of one of which,
I went with my dear friends John Pemberton and Benjamin Hooten, as far as Fort-Allen,
with an invitation from the Indians assembled at Easton and the government of Pennsylvania,
to some Indians who discovered a backwardness or fear of attending the treaty.
It was thought some of them had been concerned in
the murders and bloodshed and taking of captives,
on the frontiers of our province;
and a great concern having fallen on the minds of a number of worthy Friends,
principally in Philadelphia, who freely contributed their money and time,
for promoting the restoration of peace with the natives,
I believe they were instrumental in the Lord`'s hand to appease
the revengeful nature of so barbarous and cruel an enemy.
The hearts of the Indians retaining a great love
for the memory of our first worthy proprietary,
William Penn, terming Friends his children;
I believe they were a great blessing in the hand of God,
to the government of this province for the restoration
of peace with such an enraged enemy,
who had been permitted to be a heavy rod of chastisement on this land.
Yet it was remarkable, that through the protection of the Almighty,
which was as the shadow of a mighty rock in a weary land,
few called by our name were ill used during all this calamity.

There were three Indian men accompanied us as far as Fort-Allen, Moses Tatamy,
and two others.
We travelled much in the night and through a great rain, stormy and cold weather,
to reach that place to which we came the next morning:
the captain received us very civilly,
and I thought did what he could to be of service to us,
and behaved very kindly and friendly to the Indians, which they seemed to take well.
At first sight the Indians appeared dreadful to behold,
as to anger and revenge in their countenances,
with their painted warlike looks and weapons, and were very shy;
yet after some friendly conversation,
and their receiving a few small presents which we
carried with us for some of their chiefs,
they appeared in quite a different disposition before we parted.
But we could not prevail with them to come to the treaty,
because of their word and the engagement they had made among themselves,
to depute Tedyuscung, their chief man,
to transact the business with the government on their behalf;
in confirmation of their continuing in this mind,
they sent a string of wampum by Moses Tatamy.
After a further time of free conversation they appeared still more pleased,
and as I thought out of love to us, sent two of their young men to accompany us back;
we parted with them in love, our endeavours appeared to be well taken by them,
and I hope were of service,
although none of them but the two young men came with us to Easton.
We ventured our lives, and went through hardships to perform this errand;
but through the mercy and kindness of the Lord we were preserved;
for which my soul had cause to be thankful to his great and good name.
At the other two treaties, I underwent with several faithful hearts,
a deal of inward suffering and anxiety of spirit;
a dark and dismal cloud of opposition appearing to the good work of peace.
But the minds of Friends being kept so as to look unto the Lord Almighty,
we had many extraordinary good meetings in waiting and thinking on him,
and his dear beloved Son Christ Jesus; and at times in those meetings,
the darkness would pass away, and the true light would shine,
to the renewing the hope of the humble; and the Lord,
magnified be his name! prospered the endeavours of those faithful labourers,
who had at heart`" this desirable work of peace,
and I believe they will be heirs of that blessing,
wherein Christ terms the peace makers "`Blessed,`"
and calls them the "`children of God.`"

In the year 1757, I met with a near trial in the death of my eldest daughter Abigail,
who departed this life the 23rd day of the fifth month,
in the twenty-first year of her age,
which great change I hope to be her everlasting gain.
Some of her last words were,
"`Sweet Lord receive my soul;`" and went from this world in the bloom of life,
in acceptance I hope with God;
my wife`'s mother departed this life on the 29th of the first month, 1753,
and I hope is at rest with the Lord.
This burial of my dear child, made the eighth out of my family,
and after all these many strippings and trials, I have found it good to trust in God,
and do my best endeavours.
My dear daughter Sarah and myself were now all of my family,
and the Lord`'s blessings and mercies continuing to accompany us,
with the near unity and company at times of faithful loving Friends,
would unite my heart to the flock and family of Christ my dear Lord,
and to those that are within the walls of the salvation of God.
Great has been the satisfaction that I have received
in communion with those who are of Jerusalem,
for "`Peace is within her walls, and prosperity within her palaces.`"
Oh! the goodness and kindness of a compassionate God,
in helping and defending me a poor creature,
and blessing the labour and travail of my soul in his righteous cause,
with the enjoyment of peace at times, beyond my ability to set forth; glory,
honour and praise to his great name forevermore!

A weighty concern attending our yearly meeting in 1758,
for a further reformation from the practice of keeping slaves for term of life,
several Friends with myself,
were appointed to visit those members of our religious Society, who held them in bondage,
in order to advise for their liberty; it being believed by the truly conscientious,
to be a great iniquity to keep them or their children,
and children`'s children in perpetual captivity.
Agreeably to this appointment,
I went in company with my friends John Scarborough and John Woolman,
to several such families in Chester county,
to whom I hope we faithfully discharged our duty.
On our return from this visit we were at a burial at Uwchland,
and at the monthly meeting at Goshen, where we met our friend Joseph White;
and to answer the appointment of our yearly meeting for
settling the western quarterly meeting at Londongrove,
I went with the above named Friends to the ministers`'
meeting held for the first time at that place,
which was on the seventh-day of the week.
Next day I was at New-Garden meeting, and on the following day,
being the second of the week, at that at Londongrove,
held for worship and the discipline of the church, which was very large,
and I hope favoured in a good degree with the best wisdom;
our friends Samuel Spavold and Mary Kirby, from Old England,
were also at this quarterly meeting.
We had been the week before at the quarterly meeting at Concord,
which I hope was of service to many.
After Londongrove meeting I returned homewards, in company with our friends Joseph White,
Israel Pemberton and several others, as far as Chester,
where some of us parted with our friend Joseph,
he intending to embark there in the service of Truth,
on board a vessel bound for England.

Shortly after this journey I went to Mount-Holly meeting,
and to the quarterly meeting at Crosswicks,
and joining company with my friends John Sykes and John Woolman,
performed visits to many places where they had slaves in bondage,
and I hope in true love; after which, and a solid meeting at Mansfield,
I returned home with great peace in my own bosom.

Having in the year 1757 made some progress in company with my friend John Pemberton,
in a religious visit to the families of Friends in this city,
both of such as were in unity, and those who made some profession among us,
we proceeded on, and in the year 1760,
completed the visit to above five hundred families in the city, the Northern Liberties,
and over Schuylkill.
It gave relief to my mind, that we were enabled to accomplish so weighty an undertaking,
which was kindly received, and I believe by many in that love,
with which the Lord by his counsel and goodness accompanied us from place to place;
I hope they were seasons of tender visitation to many souls.
From the time we began this visit I was mostly at home,
only as I performed the journeys before mentioned,
and at some other times visited the neighbouring meetings in Pennsylvania and New Jersey,
wherein I trust I was in a good degree clear in the sight of the Lord;
my heart being given up at times to his blessed requirings.

In a short time after this family visit, I went as far as Maiden creek,
in company with my friend James Starr, and was at an evening meeting,
which was large and edifying, held in his father`'s house.
From there I went to Reading, Exeter, the Forrest, Jacob Thomas`'s, and New Providence,
and had large meetings at several of these places, much to my own relief and comfort,
and I hope to the satisfaction of others.
I found Friends thereaway to be loving and tender-hearted,
which nearly united my spirit to many of them, as sheep of my heavenly Father`'s fold;
and I trust as they are faithful to divine knowledge,
that the Lord will prosper his work among them.
My worthy friend Ellis Hugh, accompanied me to several of these meetings,
and his gospel labours were acceptable; after Providence meeting,
I went to an evening meeting belonging to Plymouth, and the next day came home.

In a little time after I went with my friend Joseph Marriot to
a large general and youths`' meeting at Newtown in Bucks county,
which held part of two days, where I met with a kind reception,
and was favoured in the Lord`'s love,
to enjoy his living presence among his children and people thereaway.
Then returning home to our quarterly meeting,
my dear friend Samuel Nottingham from Tortola was there,
and at the youths`' meeting the next day,
when the Lord`'s saving presence was made manifest among the young people,
to the rejoicing the upright in heart.
The next meetings I was at out of town were a general meeting at Darby,
one at the burial of Robert Thomas at Abington, and the first-day meeting at Byberry,
which were large solid seasons,
wherein I found an openness among Friends in the love of the gospel;
as also where I visited the sick and the families of some Friends.
I was at a first-day meeting at Haddonfield, and a large meeting at Chester,
at the burial of Robert French, a Friend in the ministry,
who was much beloved and valued as a good example among Friends where he had lived,
I thought these meetings were owned with the best
of help and instruction in a good degree,
for the profit of the people.

I attended a large meeting at Plymouth in Pennsylvania,
on occasion of the burial of Joseph Wain,
at which was also our friend Jane Crosfield from England,
who bore a large and living testimony to Truth,
and in which meeting gospel labour was bestowed with
design for the everlasting benefit of the people,
which I wish may turn to the good of their never-dying souls.
I visited Fair Hill, and was at a large meeting at Germantown,
at the burial of Derick Johnson, and at the first-day meeting at Frankford,
in which meetings I found a degree of openness, to bear a testimony to the way of Truth,
and I hope the spring of life was opened to the comfort
of some tenderhearted ones among them.

Having been under a weighty concern of mind in gospel love, for several years at times,
to visit the southern provinces on this continent,
I acquainted Friends at our monthly meeting with the exercise that lay upon me,
with which they having unity, were free to allow me their certificate,
and on the 19th of the twelfth month, 1760, I left my outward habitation,
and my daughter Sarah to abide with my kind friends Reuben and Margaret Haines,
during my absence.
Isaac Zane being my companion on this journey,
we set forward accompanied by many loving Friends several miles over Schuylkill,
when we parted in tender love, and went home with our friend Robert Valentine that night,
and had a solid meeting the next day at his house in Downingstown;
after which we went on and reached Lancaster,
and the next day were at their first-day meeting, which, though small,
was attended with life and some degree of near unity.
Isaac Whitelock was so kind as to conduct us to the Susquehanna,
and further to several meetings;
it was with great difficulty through much ice that we crossed over this river.
From there we got to Yorktown, and had the next day a tender edifying meeting there;
the day following we crossed a river through which our horses were swam,
and went to Newberry meeting in the Redlands, which was a tender comfortable season.

We got on our way to Warrington, Huntington, and Monallen,
which were meetings I hope mostly to solid advantage, and some of them pretty large;
next to Pipe creek, Bush creek, and Manoquacy, in the government of Maryland,
where we had small meetings.
The first was a solid season; the others were attended with hard labour,
which I hope was received in love.
After the last meeting, we went forward, crossing the river Potomac into Virginia;
the next meetings were Fairfax, Goose creek.
Potts or the Gap,
some of which were largely favoured with solid comfort and satisfaction,
there appearing many dear Friends with whom I had near unity in spirit.

From the last place we travelled till we got over Shenandoah river,
and lodged at Joha Vestal`'s, where we had a solid season in the family;
a deep snow falling that night,
made it the more difficult for us to get forward
the next day to William Jolliff`'s beyond Opeckan,
which after a long cold ride we reached, and were received in love.
Next day we were at Hopewell meeting, being the first-day of the week,
and at their monthly meeting the day following, both which were solid seasons;
the next meeting was at Maurice Rees`'s,
in which there appeared to be a necessity for an amendment in +++[+++walking in]
the way of Truth.
From there we came to the widow Lupton`'s at Back creek, and had two meetings,
weighty to my spirit, and I hope to the edification of others;
I thought there was a number of valuable Friends in these parts.

We had a large meeting of Friends and others, in the court-house, at Winchester;
after it was ended,
several persons of note not professing with us behaved in a very loving friendly manner;
in going from there I possessed sweet peace in my own mind, and went to Robert Haines`'s,
where we rested one day.
On first-day was at the meeting at Crooked-run,
to which came many people who did not make religious profession with us,
and behaved with solid attention, and I hope it ended to the honour of Truth.
Next day we went a great distance from Friends, passing over rivers, creeks, and ice,
and over mountains, and much troublesome travelling,
accompanied by Robert Haines and Richard Ridgway, two hopeful young men,
to whom my spirit was united in tender love.
We were hard set to get entertainment and lodging;
late at night some of us reached a small house, in which was a great family,
who were gone to bed.
We were let into the house, which was an open cold place,
and the people were as kind as we could expect, endeavouring to provide us with lodging,
but it was so cold I could not lie long,
but got up and sat by the fire great part of the night.
To secure our horses they were put in a little square pen, scant of provender.
In the morning, after some friendly conversation with the family, we set forward,
and came to John Douglass`',
and the next day had a large and pretty good meeting at the said Friend`'s house;
from there we came to Camp-creek, Forkcreek, and Genito, and were at meetings,
some of which were large,
and in a good degree attended with the spring of life and power.
After the last mentioned meeting we crossed James river the next day,
and another river not far distant, and were at a meeting at Amelia the day following,
in which I had some comfort of mind; it was pretty large.

From John Johnson`'s we travelled a great distance to South river,
and being overtaken by the night were lost by taking a wrong road,
which occasioned us to travel many miles extraordinary,
and were hard set to find any house;
but by hearing a horse`'s bell we took to a little path,
which brought us to William Pane`'s,
and by calling he came and conducted us to his house, and was kind to us.
After feeding our horses, he guided us to Sarah Lynch`'s, and by the time we got there,
it was about half past four o`'clock in the morning; she was a tender loving Friend,
who entertained us kindly; we rested a few hours,
and then went to their week-day meeting, which was small but solid.

Next day we had a pretty large meeting of Friends and others at the same place,
in which tenderness of heart appeared among them; the next day we went to Goose-creek,
accompanied by several Friends, a long ride and a rough hilly road,
and were at a meeting there on the first-day of the week, I believe to some good service.
That night we lodged at Peter Holland`'s,
lying down in one room like a flock of sheep in a fold,
being sixteen in number with the Friend`'s family; he was a kind hearted man,
and did what he could to accommodate us with house room and otherwise,
which I believe was to the satisfaction of our company--we had here a solid meeting;
at the two last meetings there were several tender Friends lately convinced.

After near two days ride and passing over Stanton river, we came to Joseph Collins`'s,
had there a solid meeting and rested one day; after which we were at Banister meeting,
where came many people, and I hope it was a profitable season to a remnant;
we went from there to Richard Kirby`'s and had a large meeting;
they appeared to be a tender seeking people, and much in the spirit of love.
We then came near the river Dan and lodged;
crossed the ferry next day to James Taylor`'s in North Carolina, being many miles,
and were overtaken by the night before we reached the house.
We lodged there two nights, and had a meeting at Eno,
which was large and I hope to edification;
then we went home with Joseph Maddock and lodged,
and next had a meeting at the Hawfields, and the Spring, which though small,
I thought were good meetings, and Friends glad to see us.

From Thomas Lindley`'s, where We lodged, we went to the monthly meeting at Cane creek,
and were also at their first-day meeting, which were large,
but times of suffering to my mind; from there we proceeded to Rocky river, the Center,
and Deep river, some of which meetings were large,
and I trust favoured with the extending of God`'s love and
merciful visitation to the souls of the people.
We also had a comfortable solid time at Richard Reason`'s,
whose wife had been a valuable servant to the church,
but was now grown old and feeble and much confined through infirmity of body;
but I thought lively and sensible in the best things.

We were likewise at the quarterly meeting at New Garden, at their ministers meeting,
and that for business of the church, also at their first-day meeting;
the last two were large and weighty seasons,
wherein the divine presence was witnessed to the refreshment of the solid minded.
Next we attended a meeting at William Coxe`'s, where were a pretty many Friends;
it was attended with hard labour, which I wish may not be lost,
for I trust it was honestly discharged among them.
We went forward to Solomon Coxe`'s and Cornelius Tyse`'s,
and had a meeting at each place,
to the last of which belonged several newly convinced Friends and tender people,
with whom I had solid satisfaction.

Hence we went to Pee-dee, accompanied by Jeremiah Picket,
lodged one night in the woods on our way there,
and had a laborious meeting at this place, attended by a considerable number of people,
I thought, for this remote part of the world;
it had a humbling reach on some who were present, I hope.
We lodged at William Hall`'s, and from there went to the Wateree in South Carolina,
accompanied by William Hall, Francis Clark, Jeremiah Picket, and Andrew Morman,
lodged at Samuel Wiley`'s. We had a tender broken meeting at the meeting house,
much to satisfaction, and a pretty good time at the house of a Friend who was indisposed;
also a solid time with a number of Catawba Indians, and then returned to Pee-dee.

In going to and returning from this place, we were two nights in the woods,
but fared pretty well,
the weather being fair and having provisions for ourselves and horses;
and my mind being +++[+++divinely]
supported, I enjoyed peace in the journey.
On our return to Pee-dee, we were at their first-day meeting, visited some sick families,
and had a solid evening meeting at Francis Clark`'s, where we lodged.
The next day set forward for Cape Fear; in our way were one night in the woods,
and a great snow falling, the weather was disagreeable,
either to stand or to lie down before our fire.

Next morning we set forward and got to Richard Bradley`'s, at Cross creek in Cape Fear,
where is a small town lately built; we had a meeting in it,
to which came a pretty many people, some of whom were Friends,
and it was to some satisfaction.
Our next meeting was at the meeting-house at Dann`'s creek, which was a laborious time,
and I wish it may have a good effect on the minds of the people,
for I trust they were faithfully warned,
both on account of their slothfulness in the things of God, and the things of this world.
We came to John Newberry`'s and lodged,
and the next day went towards Upper Falling creek, on Neuse river,
stopping in our way at Jonathan Evans`'s, where we had a tender time in the family,
which I believe was well received, although he did not make profession with us;
his wife was a valuable Friend, and I understand had a gift in the ministry;
he conducted us several miles on the way, and parted with us in love.
After we left this man`'s house we parted with Jeremiah Picket and Francis Clark,
who had accompanied us four hundred miles;
at night we stopped at a house to enquire for entertainment,
where was a woman and several children.
She gave us liberty for house room, and there being no bed for us we laid on the floor,
and it being cold and snow falling,
we were sometimes obliged to get to the fireside to warm us;
it was a trying time to my spirit;
yet I thought we were better off than when in the woods and snow a few nights before.
Next day we came to Thomas Coxe`'s, where we had a meeting,
and the people were warned to prepare for their final change;
mortality sounded aloud in these parts,
and several seemed to speak with a mournful voice,
concerning the death both of man and beast.

After we crossed Rock-fish, Cape Fear, and Neuse rivers,
we were accompanied by Richard Coxe to John Radcliff`'s,
and having a pretty large satisfactory meeting at Lower-Fallingcreek, we came many miles,
accompanied by Moses Ratcliff to James Ross`'s,
a dear Friend not long convinced of the way of Truth,
who did all he could to make us welcome.
We had here a uniting relieving time in waiting upon God,
and after a meeting of religious service at Henry Horn`'s in Edgcomb on Tar river,
and a solid time in his family, the next day we rode many miles,
accompanied by James Ross to Moses Hall`'s and lodged,
in whose family I was much comforted and united to such
I believe that kept their places in the blessed Truth.
After an open tender meeting at Rich-square, and a near parting with several Friends,
we came to John Cowpland`'s, where we had a meeting to solid advantage,
and I hope profit to the people; we then went to Thomas Cowpland`'s and lodged,
and the next day crossed a pretty large river, and after a long ride,
through a dirty tiresome road,
we reached Thomas Newby`'s. He and his wife are worthy kind friends to
the Lord`'s servants and particularly helpful to me in several respects.

On the first-day of the week we were at a meeting at Wells, which was large,
and I thought solidly favoured with the consolation of Truth.
Several advices were given forth in the love and fear of God,
and humble contrition of heart I hope was offered up before the Lord that day;
the two next meetings were Old Neck, and Little-river, both which were large,
and in the openings of the gift of life I had to discharge
that trust which I apprehended was required of me,
and found a choice number of loving Friends hereaway, both old and young,
with whom I had to rejoice in our heavenly Father`'s love.
We lodged at Thomas Nicholson`'s and went to the next meeting at Simon`'s-creek,
and New-beguncreek, which were large and solidly edifying,
the current of love and life running freely among the people,
to the watering the heritage of God; we were also at a Friend`'s named Trueblood,
where was a great gathering of people.
The word of life was freely preached among them; they were well-behaved,
and several parted from the meeting in a sober friendly manner;
the next meeting was over the river by Old-Neck, when it was ended we returned,
and were at the burial of a child of Daniel Saint.
Had a solid meeting at his house; from there we came to Joseph Newby`'s and lodged,
and the next day, being the first of the week, we were at Piney-woods meeting,
which was very large and comfortably owned with life and power.

From Thomas Newby`'s we went to a distant meeting, which was a hard suffering time;
we were also at the monthly meeting at Wells, which was very large and to edification,
being the last meeting I was at in North Carolina,
after which I parted with several Friends in much love,
and I hope many of those opportunities will be remembered by the living, with my soul,
and I wish it may be with thankfulness to the Lord, that is worthy of all the praise,
honour and glory!

We came next day into Virginia, and were at a meeting at Sommerton,
which was to some satisfaction; the next was at Lazarus Johnson`'s,
from which we went to John Denson`'s and lodged,
and the day following were at a meeting at Black-creek,
which was attended with solid instruction,
a considerable number of Friends belonging to the same;
we then came to James Stanton`'s and Joseph West`'s and had meetings,
to the last of which came a colonel of the county, and a considerable number of people,
and the good power of Truth prevailed among us that day, which I hope was of service.
Then passing over Nottaway ferry we came to James Jordan`'s and lodged,
and from there to the Western-branch monthly meeting,
at which were many people and it was an open time;
the next meetings we went to were at Rasconeck, and Chucatuck,
which last I was informed had been one of the largest meetings in Virginia,
but is now reduced to two or three families; things were at a low ebb among them,
the other somewhat open, and attended by several who did not profess with Friends.

From James Denson`'s we came over Nansemond-river to Samuel Fitzrandal`'s and lodged,
and on the seventh and first-days of the week,
we were at the spring yearly meeting at Nansemond,
which I hope was in the main well and somewhat large, considering the season,
which was wet.
We were at Elizabeth Burleigh`'s one night, where we had a solid evening meeting;
when the yearly meeting was over, we went home with Samuel Jordan,
spent a little time with him, then went with Thomas Newby to Joseph Scott`'s and lodged,
and the next day were at a meeting at William Hallowell`'s,
that gave me some ease of mind.
Lodged at Jacob Cornwall`'s, and the next day we were at Surry meeting, which was large,
and attended mostly by people not professing with us, who behaved soberly;
I believe it was a profitable season and ended well;
the next was the monthly meeting at Black-water, that part for worship was large,
and the good presence and power of the Lord prevailed among us,
to the uniting our hearts to each other,
and I thought the meeting for business might have been well,
had not worldly matters been brought in among them.
From Anselem Bayley`'s we went to Burleigh meeting, which was large and solid;
from there we came to Gloster Hunnicut`'s, and had a large meeting,
mostly of people who did not profess with Friends,
which was owned with Divine strength and power, wherein I had comfort of mind.

We came to Edward Stabler`'s and lodged,
and on the first-day of the week had a very large meeting at Petersburg,
to which came a great number of people from the town and country,
and many Friends a considerable distance,
and through the Lord`'s helping hand his great Name was praised, who is worthy forever!
The next large meeting was at the burial of an ancient Friend near Wainoak;
it was held in an orchard, was an awful solid time,
and of brokenness of heart among the people;
the next was at William Butler`'s at the marriage of his daughter,
where were many people, and the meeting was satisfactory in a good degree.
We returned to Edward Stabler`'s and stayed one night;
after which we went forward and crossed James-river,
accompanied by our kind friend John Pleasants and his wife,
who took us to their house and gave us a kind welcome,
and were the next day at Curies meeting, which was large though not many Friends;
it was a laborious time, things being low as to the growth of Truth.

After this meeting we came to John Pleasants`', kinsman to the last mentioned John,
and lodged one night, whom we had met with in North Carolina,
and was a loving friend and brother to us; he was with us at many meetings,
and his company valuable and serviceable to me, and my spirit was nearly united to him.
From his house we went to White-Oa`'k-Swamp meeting,
which was large and to good satisfaction; the next day we were at Wainoak meeting,
where came a colonel and many people of note, both Friends and others,
who behaved soberly, and the meeting ended well.
From there we went to Skimino, and in our way crossed Chicahomony with John Pleasants,
who had been our companion in several places, and another Friend who were our guides,
and on the first-day of the week were at a meeting at James Bates`'s
where came a large number of people not of our Society,
and many Friends from a considerable distance.
I hope it was a time of profit and edification,
for which my soul had cause to be thankful to the Master of our assemblies;
we had also a solid tender time the same evening at Fleming Bates`'s,
when things were spoken to in the spring of life and power,
and our hearts were united together in gospel fellowship.

Next day we came a great distance to Robert Ellison`'s and lodged;
and the day following were at Black-creek meeting,
which was large and a weighty laborious time;
although I had hard labour I possessed peace of mind;
the next meeting was at Chicahomony-Swamp,
at which were many people not of our persuasion, and it was a solid good opportunity;
from there we came to Joseph Parson`'s, where we had a meeting in his barn,
which I hope tended to some good service, there being a pretty many people present.
The next was at Cedar creek, where were present several reputed great men,
and many besides Friends and others; it was a solid time,
which afforded sweet peace to my mind; we went from there to Micajah Terrell`'s,
Samuel Margrave`'s, and John Cheagle`'s, and were at their first-day meeting at Caroline,
which was very large,
and strength was afforded to ease myself of the burden
that I had long borne towards this part of the world,
and was I hope an awakening time to some then present.
After it ended I parted affectionately with several dear Friends,
it being the last meeting in Virginia,
only a solid season at a Friend`'s house where we lodged;
then went forward with Micajah Terrell for the yearly meeting at West river in Maryland.

We crossed Rappahannoc and Potomac rivers, and another ferry,
and got to the Cliffs to William Harris`'s, who received us kindly,
after a long wearisome ride; next day we had a meeting at the Cliffs,
at which were many people, it was a solid time,
and I hope the witness in some was reached; we were also at a meeting at Herring creek,
which was small and I was doubtful almost lifeless as to the true zeal for divine worship,
which gave me pain of heart among them.
The next day we came to Philip Thomas`'s at West river, and remaining there,
attended the yearly meeting, which lasted several days;
it was large and greatly favoured with the visitation of God`'s love,
through Jesus Christ, to the people, and was a uniting time to the faithful.
When this meeting ended, my companion Isaac Zane left me, in order to return home;
I went to Joseph Richardson`'s and dined, and then to visit my aunt Mary Henderson,
my father`'s sister, whom I had not seen for several years, and thought she was dead,
until a Friend informed me at the time of this yearly meeting of her being living.
I stayed there one night, and although she did not profess with us,
being of the church of England, so called, I believe was a religious woman,
and of good repute; she was glad to see me, and I thought had a respect for Friends,
and parted with me in a kind tender manner, and not long after departed this life.

I went to a meeting a few miles from there, which was solid,
and from it home with Gerrard Hopkins,
and the next day with several Friends to Indian-spring meeting,
which was to good satisfaction; lodged at Richard Snowdon`'s,
and was next at Sandy-spring meeting, where came Friends from several distant places,
and it was a solid time.
From James Brooks`'s I went home with Henry Pierpoint, and was the next day at Elkridge,
which was a large meeting, and faithful labour in gospel love was bestowed among them,
which I wish may have the desired effect.
Lodged at Joseph Pierpoint`'s, and was the next day at Patapsco meeting,
which I hope was in the main well; then went with Samuel Hopkins to his house,
and the next day to Gunpowder meeting, where the living fountain was, I thought,
in some measure unsealed to edification and comfort.
I also went to the meeting at the Little-falls, at which were many people,
and the good power of Truth prevailed among us, I hope to solid satisfaction;
lodged that night at Henry Wilson`'s, and the next day was at Bush river meeting,
many Friends being there; it was a time of comfort to my mind.
I went home with James Rigby and his wife, stayed one night,
and next day attended a large meeting at Deer creek,
which was an awful heart-tendering season, wherein the truly living, with my soul,
had cause to ascribe thanksgivings and humble praise to the Lord our God, who is worthy,
with his beloved Son Christ Jesus, the only head of the true church,
both now and forever more.
Amen!

Then passing over Susquehanna ferry, the next day being the first of the week,
I went to West Nottingham meeting, which was somewhat large and solid,
and got to William Jackson`'s and stayed the night and the day following,
being the 25th of the fifth month, 1761.
Through the kindness and wonderful providence of the Almighty,
that had been merciful and good in preserving and helping me through this trying journey,
I arrived at my own habitation,
and found my daughter and things well as to my own concerns,
and a kind reception with my dear friends, whom I was glad to see once more,
and enjoyed a share of peace to my own soul; may all praise, honour,
and glory be given to Him the great and awful Majesty in heaven!

[.embedded-content-document.epistle]
--

[.letter-heading]
Epistle to Friends at their monthly meeting at Perquimans in North Carolina.

[.signed-section-context-open]
Philadelphia, Tenth month 2nd, 1761.

[.salutation]
Dear Friends,

In a measure of the same love that attended my mind when present in body among you,
I take this freedom now to salute you in spirit,
wishing the health and prosperity of the precious Truth in every particular
branch thereof We as a people profess it to lead us into all truth,
which is the greatest profession in the world,
and is the most sure and safe for all the truly living and
acting members of the mystical body and church of Christ,
to be guided by the wisdom and nature of it in all things, to the glory of God.

And dear Friends, keep in the peaceable wisdom and love of God,
for "`God is love;`" and Christ has commanded us "`to love one
another,`" as also one of his servants advises to love as brethren;
let nothing break the unity that is in the true faith
and peaceable spirit of Christ our holy head.
But dear brethren, be of one mind in his righteous cause,
in a particular manner in maintaining decency and good order in his church,
that his church may be built and supported by living stones,
and his vineyard kept clean and thriving with living branches,
such that may bring forth much good fruit to the praise of God!--My spirit,
according to my measure, is often with such among you,
that have the weight of the Lord`'s work on your shoulders,
and I have many times been comforted in remembering the refreshing and edifying
seasons of the power and presence of Christ that we have enjoyed together,
in that ability he was pleased to afford unto us, when it was my lot to be in your parts.
I thought myself to be in a good degree clear as to my religious duty;
only with respect to the meeting for business, it gave me some pain of mind,
that there was no distinction made between such that were of our own family,
Friends in unity, and those of other persuasions,
by allowing them the same privilege with Friends, in sitting in those meetings,
to see and observe the remarks on your own proper business.
They having no right as members in the Society, it must needs weaken the testimony,
and the right labour of faithful Friends,
and expose the management of such meetings to the
vain and libertine conduct of the world,
and so cause the way of Truth to be evilly spoken of,
as also give great pain and exercise to the sincere-hearted.

It is in much love and tenderness, that I have thus expressed myself in this respect,
and to ease the weight that has been on my mind, from a thought of that unusual custom,
not allowed among Friends in other places where the authority of Truth takes place.
I wish it may be reformed among you so as to have it otherwise,
which I believe will be more to the advantage of the church among yourselves,
and greater satisfaction to the Lord`'s servants
that may come to visit you in gospel love.
It had been better for me, I have thought,
had I embraced the opportunity to have eased my spirit when we were together,
but a backwardness prevented, which I had rather had not happened;
but if this is received in the same love that it is intended,
I hope it may answer the same good design.

I do not in the least desire by what I have mentioned,
that any disrespect be shown to those of other religious denominations,
or to prevent their coming to our meetings for worship,
or any Christian office of love in any suitable way and manner,
so that it be consistent with our holy profession.
But with respect to what I have hinted,
I have thought it an imposition and disorderly in such to expect any such privilege,
and I wish that elders may exert their authority,
such that the Holy Spirit may make overseers, and that they may be preserved,
so as to look well to themselves, and to the flock of Christ;
and that the same powerful faith that has been the
foundation of the righteous in all ages,
may be their strength and support, so as to rule well, and to be worthy of double honour;
they labouring and enduring in the spirit of love and meekness,
to do the Lord`'s work with pure hearts and clean hands,
seeking that honour that comes from God only,
that he may be pleased to fulfill his gracious promise, to honour those that honour him,
that by their being good examples to the flock, the youth and all that go under our name,
may follow them as they follow Christ.
My heart is tenderly affected before the Lord on account of the rising youth,
who are coming upon the stage of life, and are reached I believe, many of them,
by the same good Shepherd`'s voice that visited many of us,
by the powerful call of grace and faith to salvation,
that they may daily partake of heavenly bread and nourishment to their souls,
so as to grow strong in the Lord, and in the power of his might,
and they kept faithful to divine knowledge and the blessed yoke of Jesus Christ,
so as to live in the fear of God,
and prosper in those things that are consistent with Truth`'s testimony,--obedience
to parents,--true moderation,--plainness of speech and apparel,--and
out of the vain conduct of the ungodly;
for the ways of the ungodly shall perish.
And let all the tribulated and faithful followers of the Lamb,
be encouraged to keep your heavenly places in Christ, for he has told us,
that "`Greater is he that is in you,
than he that is in the world;`" and let none "`be weary in well doing,
for in due time we shall reap if we faint not.`"

In true love I salute you, and wish that grace, mercy and peace may increase,
and be multiplied among you.

[.signed-section-closing]
Being a real lover of Zion`'s prosperity,

[.signed-section-signature]
Daniel Stanton.

--
