== Chapter V

Being favoured with health,
I was enabled to perform my outward employment with diligence,
and sometimes visited the meetings of Friends in Pennsylvania and New Jersey,
where in several places we were owned with our heavenly Father`'s love,
to comfort and edification.
A religious concern reviving in my mind, that I had felt for a considerable time,
to visit Friends on the Eastern shore of Maryland,
and the three lower counties in the territories of this province,
having the unity of my dear brethren at home,
I set out on the 3rd day of the first month, 1763, being the first-day of the week,
and came to Chester, accompanied by several dear Friends of our city,
and was at a meeting there, which was a comfortable tender season of gospel love.
The same evening had a large laborious meeting at Wilmington,
in which I hope I was clear as to my duty among them;
the next day accompanied by Thomas Shipley, who was my companion in this journey,
came to Lewis Clothier`'s and lodged, and I thought our being there was of some service.
From this Friend`'s we went to Sassafras meeting, where came a number of people,
with whom I hope the power of truth had a tender reach on the hearts of several;
next at Cecil meeting,
in which the spring of life was I thought opened to solid comfort among us.
We had the next day a meeting at Chester meetinghouse, attended with hard labour,
and one in the evening at James Claypool`'s in Chester-town, which was solid;
from there we came to Queen Ann`'s, and had a large satisfactory meeting,
in which I had some relief of mind,
I thought it was a time of tender visitation to the people.

We then went to Isaac Turner`'s and lodged,
having in the evening a comfortable sitting in the family; they were kind and friendly;
from there to Tuckahoe, where we had a blessed meeting,
and on the following first-day of the week were at Tredhaven,
which meeting was solid and edifying.
From there we went to Joseph Bartlet`'s,
where was a large exemplary family and no slaves, and had a good solid sitting;
the next day had a large open meeting at the Bayside,
mostly of people not of our persuasion, which I hope ended well;
after lodging at John Kemp`'s, we came the next day to Francis Neal`'s,
and the day following attended a large meeting at Little Choptank,
both of Friends and others, to some satisfaction.
We crossed Choptank river, and were at Marshy creek meeting, which was a trying time,
both on account of the coldness of the weather and a suffering cold house to sit in;
lodged that night at William Edmundson`'s, and the next day set off for Lewistown,
accompanied by Benjamin Berry, and after a long ride we got to Samuel Rowland`'s,
who received us kindly,
and was helpful in getting a large meeting for us in the courthouse in the town;
in which I trust they were faithfully warned and advised in the love of the gospel,
and in visiting that place I enjoyed satisfaction.

Then we went to Cold Spring, which meeting was attended by many people,
and I thought some revivings of life therein; the next meeting was called the Three-runs,
which many people attended, and was an awful heart tendering season;
we were next at Motherkill, where came Friends from several parts,
and various other people, and it was a solid time;
the day following we were at Little creek meeting, which was a comfortable season;
the following meetings were at Duck creek, and George`'s creek,
and attended with hard labour; but I hope of service to stir up the pure mind in some.
From my kind friend Jacob Janney`'s, I came with several towards Okesson,
and on our way stopped at a house where were several in family,
with whom we had a solid opportunity,
which I believe gave satisfaction to them as it did to us; on our way there,
parting with my companion Thomas Shipley, I came near Okesson and lodged,
and was the next day at a meeting there, which was a suffering time to my spirit.

I then went to the quarterly meeting at Londongrove,
where were Hannah Harris and Elizabeth Wilkinson, two worthy Friends from Old England;
the meeting was very large and I hope of service;
then took several meetings in Chester county,
some of which were large and attended with relieving help,
in which I enjoyed much comfort and unity among Friends,
as I visited the several particular meetings; which were Kennet, Center, Birmingham,
the Forks of Brandy wine.
West and East Cain, Nantmill, Pikeland, Uwchland, Goshen, Newtown, Middletown,
and Providence; to the last of which came my son-in-law Benedict Dorsey,
with whom I came home to my habitation, in the enjoyment of a share of peace;
having visited the afflicted, and several Friends families,
and I trust faithfully laboured,
travelling through cold and hardships and sometimes deep probations of spirit;
but have had reverend cause to be humbly thankful to my blessed Lord and Master,
who greatly helped I hope to his own praise, to whom be it ascribed forever more!

On the seventh-day of the fourth month, 1764, with the unity of my friends at home,
I went towards Buckingham, was the next day at that meeting,
with Israel and John Pemberton and Joshua Emlen,
which was large and to some satisfaction.
After this meeting, Joshua Emlen being my companion,
we proceeded to Kingwood in New Jersey, guided by Samuel Eastburn,
lodged at Robert Large`'s,
and the next day had a large meeting at this place to edification and comfort;
from there to Richard Lundy`'s, and after a stay of two nights,
were at a meeting in his house, where was a number of tender-hearted youth and others,
in which the Lord was pleased to favour us with his blessed presence to satisfaction;
the Friend informed us, that he had seventy children and grand children,
some of whom were valuable Friends; this place is called the Great Meadows.

The next meeting was near Pawlingskiln,
in which a remnant was broken and contrited before the Lord,
and I hope it was a time of Divine visitation to those who were present.
We went near the head of the waters at the Drowned Lands, so called,
lodged at Elijah Pollard`'s, and next day being the first of the week,
had a large meeting at his house,
where came a mixture of people as to religious profession,
and the Lord was graciously pleased to appear among us,
and I understood that some acknowledged to the truth,
for which my soul had cause to be thankful,
it being a low time to my mind before the sitting of this meeting.
We lodged at Richard Gardner`'s, where we had a meeting the next day,
at which there was a sergeant of the army, who,
after the meeting went in company with us many miles on our way towards North river,
and confessed to the principle of Truth as professed by us,
and I thought that if he would resign his office as to outward war,
and be faithful to knowledge, he might make a soldier for Christ;
I found his spirit near to mine in many things relating to Truth,
and parted with him in love.
We lodged that night at an inn,
and the next day crossed North river ferry called Fish-kill,
and came to Joshua Sherman`'s, at whose house we had a solid tender meeting the next day,
of many people, Friends and others; then came to Oblong, lodged at Benjamin Ferris`'s,
and the next day were at that monthly meeting, which although the day was very stormy,
was attended by a number of Friends, and I thought with unity and satisfaction.

Next day we came to John Hoag`'s and had a pretty good opportunity with many people;
the day following had a long ride to Salisbury in Connecticut, lodged at Joshua Whitt`'s,
and on the first-day of the week were at a meeting in that place,
where came a number of professors,
(but few of our Society) among whom we had an open comfortable meeting.

We proceeded the next day towards a place called the Nine Partners,
stopping on the way at a Friend`'s house to dine; had a solid time in the family,
and the day following were at a meeting at the Nine Partners, which was large,
and Truth reigned in a good degree among us,
I hope to the praise of the Master of our assemblies.
Passed over Wapping creek, and had a meeting at a Friend`'s house,
where came many people, it was a heart-tendering time,
the next place where we had two meetings was Oswego, the first of which was small,
but a comfortable time; the other was large,
and the word of life prevailed in a good degree among us,
for which a remnant had cause to be united in praise
and thanksgiving to the Author of life and power.
From there we went towards Oblong,
and the next day visited our two ancient Friends John Hoag and wife,
where came several of their neighbours and sat down with us;
the Divine presence appeared among us in a powerful manner in a little mean cottage,
wherein my spirit was refreshed before the Lord,
and we had a kind reception with those present.

We were next at Oblong meeting, at which was a large number of people,
who were faithfully warned and advised to keep in the fear of God,
and Truth seemed to have a reach on the hearts of some;
then went to Dobson Wheeler`'s at New Milford in Connecticut,
and the day following we were at a large meeting in the meetinghouse,
where was a marriage, and a laborious time to my spirit among the people,
but I hope of some service,
their behaviour being in the main as well as might be expected,
being mostly of other professions.
We returned to Oblong, and were at the week-day meeting,
which was a time of poverty and suffering in spirit in some degree;
we stayed their quarterly meeting of ministers and that for business,
also their first-day meeting, the last of which was very large,
and in a good degree owned with the best of help, I hope to the glory of God,
and was a time of loving parting with a number of dear Friends living thereaway.
We went home with Samuel Field, and had a meeting at a place called Peach pond,
which was pretty large and solid;
and although a great part of this journey thus far was mountainous, the roads stony,
and wearisome and trying to body and spirit,
yet through the Lord`'s lovingkindness and tender mercy,
I at times enjoyed peace of mind being enabled to perform in this hard travel,
what I apprehended to be required of me by Him who
is worthy of praise and thanksgiving forevermore!

The two next meetings were Amawalk and Shappaqua, which were large,
and I hope well in the main; from there we came towards a place called the Purchase,
lodged at a Friend`'s house, and in the night was a time of rain, lightning and thunder,
by which, some distance from this place, as we were told, a poor black slave was killed,
concerning whom two brothers had been disputing their right of property,
and one of them had said that he would cut him in two but he would have his half of him;
but through the permission of divine Providence his time was shortened,
and they must resign their claim to him.
The next day we attended the meeting at the Purchase, which was large,
also visited a family in affliction, both which were solid seasons;
lodged that evening at Edward Burling`'s,
and had a solid sitting in that Friend`'s hopeful family of young people.
Our next meeting was at Mamaroneck, then at West Chester, where came Samuel Emlen, Jr.,
John Haydock, and Haydock Bowne from New York, to see us;
their company afforded much comfort to my spirit;
this meeting being attended with life and near unity,
made it a comfortable edifying season;
we had the company of Matthew Franklin and William Mott
at most of the meetings to this place from Oblong,
two exemplary Friends, and serviceable in the ministry.

We passed over White-stone ferry to Long Island with several Friends,
and Matthew Franklin took my companion and me to his house,
where we had a kind reception; the next meeting we were at was Flushing,
and they were warned against the ways of unrighteousness,
and the well-minded among them I hope encouraged.
Next day we visited several Friends in affliction, one of whom was Clements Willets,
a pious tender woman, at Bethpage, who seemed almost helpless as to bodily strength,
and told us she had been in that condition thirty-one years;
her frame of mind was heavenly,
and appeared to be well contented in the will of divine Providence;
the day following we attended Bethpage meeting, which was large and solid;
we were also at Setawket, and had a large good meeting;
from there we went to Samuel Willis`'s and lodged.
The meetings following were at Matinicock, Oysterbay, and Jericho,
which were large and solid seasons; from Jericho we went to William Lime`'s and lodged,
and on the first-day of the week were at Westbury meeting, which was very large,
and attended with hard, close labour,
but I hope in the gift of life and power that God gives.

We came that evening to Benjamin Dusenbury`'s,
and were the next day at a meeting at Jacob Mott`'s, which was large and an awful season;
we then went to the widow Pearsal`'s, who was an ancient Friend,
and a family I had long been acquainted with,
whom I had reason to remember in near fellowship in the church;
after a meeting the next day at Cow-neck, we went home with Matthew Franklin,
and attended the yearly meeting at Flushing, which was very large,
and I trust in a good degree owned with the presence of God.
Joshua Emlen left me before the conclusion of this meeting, in order to return home,
on account of his son being to embark soon for England; when the meeting ended,
I went with several Friends to Richard Hallett`'s,
and the next day crossed the Narrows to Staten Island,
and from there with Joseph Shotwell to his home.
After having meetings at Rahway, Woodbridge, and Plainfield, to some satisfaction,
accompanied by him and his wife over Amboy ferry we went to Nathan Tilton`'s,
and from there to Shrewsbury, where I attended two large meetings,
which I hope were in the main well.
I went home with James Tucker, my father`'s cousin, and stayed one night,
and the next day himself and son, and Joseph Wardel, conducted me to Squan,
where we had a large meeting, which was an open solid tender season,
somewhat relieving to my spirit.
Lodged at Thomas Tilton`'s, who the next day accompanied me to Amos Middleton`'s,
in or near Burlington county, and the day after, through the good providence of God,
my alone helper through Christ in the way of true obedience to his blessed will,
I got home to my outward habitation, being the 7th day of the sixth month, 1764.

On the 3rd day of the second month, 1766, after our quarterly meeting in Philadelphia,
I set out from home with several Friends towards Haverford;
lodged that night at George Smith`'s,
and was the next day at a large meeting at Haverford, to satisfaction,
and then proceeded to the meetings at Newtown, Radnor and Goshen, which were large,
and attended with life and the Lord`'s good presence and near unity with Friends.
I attended the quarterly meeting of ministers at Concord,
in which my mind was deeply engaged for the maintaining of gospel love and unity,
and real fellowship among ministers and elders,
and the Lord was pleased to give me an open door,
that I believe the labour was well received.

On the first-day of the week, I went to Birmingham meeting, which was large,
and they were faithfully warned in the fear of God;
the next day I attended the quarterly meeting for the affairs of the church at Concord,
which was very large, and owned with the best of favour; after this,
I was at the meetings of Kennet, Wilmington, Center, and Chichester,
some of which were very large,
and the Lord`'s heart-tendering power and presence much favoured most of those opportunities,
and Friends were affectionate and kind.
I went home with Benjamin Sharpless and wife, and lodged at his house,
and the next night at Nathan Yarnall`'s, with whose hopeful family in the way of Truth,
I had comfort of mind; the day following being the first of the week,
was at Middletown meeting, which was large, Friends coming from several distant places,
and through Divine favour, it appeared to be a solemn time; dined at Thomas Minshall`'s,
and had I hope a profitable sitting with a number of dear young people and others.
I was the next day at Providence meeting,
which was owned with the virtue of life and power in waiting upon God;
from there I went to William Fell`'s, where lived his aged father Thomas Fell,
who had been blind several years, and lately again received his sight,
whom I thought to be a living Friend in the Truth, and I hope in favour with the Lord;
the next day I was at a large meeting at Springfield,
in which I trust they were faithfully warned and advised in gospel love.

I lodged that night at Jonathan Maris`'s, came the next day to the Valley,
and the day following had a meeting there,
to which several Friends came from distant places,
and it was a time of comfort to my mind; I went home with Israel Jacobs,
crossed the river Schuylkill at Richardson`'s ford,
and attended a meeting the next day at New Providence, where many people came;
it was a time of deep and close labour, but I hope tended to edification;
then went to John Jones`'s and lodged,
and was at Gwynned or North Wales meeting on the first-day of the week, which was large,
and an open comfortable season: I then went to John Child`'s and stayed two nights,
attended a large meeting at Plumstead, in which they were warned in the Lord`'s fear,
and it appeared to be a time of profit to a solid remnant;
after this I went to the quarterly meeting at Wrights-town in Bucks county,
of ministers and for the discipline, the last of which was large,
and each owned with near unity among Friends, and gospel labour extended,
I hope to good purpose, Mordecai Yarnall and John Pemberton being also at this meeting.
The next meeting was at Makefield, which was large,
and comfortably owned with life and power in the Lord`'s strength,
and was a solemn awful season.
Went to see a sick Friend, where many Friends met;
it was an opportunity of much tenderness and brokenness of heart,
wherein I had relief and satisfaction; lodged that night at Mahion Kirkbride`'s,
and the next day crossed the river Delaware near Trenton with some other Friends.
Although a very rough passage, we were mercifully preserved,
for which my heart was thankful to the Lord.
Lodged that night at William Morris`'s,
and on the first-day of the week was at Trenton meeting,
where assembled a pretty many people.
Friends and others; and although it was a hard suffering time to my spirit,
wherein I was deeply baptized in that place,
I had some comfort in the company of some Friends thereaway.

I came from there and lodged at Marmaduke Watson`'s, and the next night at John Sykes`',
and the day following had a meeting in Bordentown, to satisfaction in a good degree;
then went to Samuel Satterthwaite`'s, and had a meeting the next day at Mansfield,
at which, considering the short notice, and it being a wet day, there were many people,
and We had a solid season together.
I went to Benjamin Field`'s,
and the day following attended the monthly meeting at Crosswicks, which was large,
and an open edifying season in the meeting for worship.
Then to Peter Harvey`'s, and the next day went to a meeting at Old-Springfield,
which was large,
and several things ran through me in the spring of life to aged and youth, as advice,
in near love to the cause of Truth, and for the welfare of God`'s people.
The day following I had a meeting at Mansfield-neck, where many people came,
and it was a time of good satisfaction;
the next day was at a large meeting at New-Springfield,
which was attended with close labour, and faithful warning extended to the people;
then went to Joseph Lamb`'s. Here I was somewhat detained by a storm of snow;
when it moderated I got forward, with my beloved friend William Jones,
to our kind friend John Ridgway`'s at Little-Egg-harbour, and the day following,
visited with him several families of Friends, and went to see Christiana Osborn,
an ancient Friend reckoned to be upwards of ninety years of age,
who was mother and grandmother to many that were valuable in the way of Truth.
We had a tender time in the family, I hope to some profit and edification.
I attended the monthly meeting at Little-Egg-Harbour,
which was in a good degree owned with divine favour, and the life of the gospel power,
and many people were present.

Being prevented by stormy weather some days from crossing the river to Great-Egg-Harbour,
till the first-day of the week,
I then came with several Friends to the upper meeting on that river,
which was large for that place, and tended to edification and comfort.
I went home with Japhet Leeds, and he accompanied me that evening to Joseph Mapes`'s,
where we lodged, and the next day were at a meeting near his house;
from there proceeded to Cape May, in company with some Fi lends.
Lodged at Isaac Townsend`'s, and was the next day at a large meeting for that place,
at the Lower meetinghouse, to some degree of satisfaction,
in which I laboured to turn the minds of the people
to Christ our free and infallible teacher,
and there appeared a tender-hearted few among them.

I then went forward to Cohansy, and had a meeting somewhat large,
and a laborious time at Greenwich, which being in gospel love,
I trust tended to edification.
I then had a solid sitting in Joseph Gibson`'s family,
his wife being much afflicted with a cancer,
by which it was said she had lost one of her eyes, and almost the sight of the other,
but was in a patient frame of mind.
The next day I went to Salem to the burial of the wife of John Mason,
on which occasion we were favoured with an awful solemn meeting;
went home with Samuel Nicholson,
and the next day had a solid sitting with an afflicted
family in our way to Lower Alloways creek meeting,
which was very large,
wherein I gave up to spend and be spent in fervent love and gospel labour,
and hope it was a blessed season to a number there present.
From there I came with several Friends to Benjamin Thompson`'s at the glassworks,
and the day following we had a large meeting at Upper Alloways creek,
much to the satisfaction of some present, in which having cleared my spirit,
I came away relieved in my mind; then went to Zaccheus Dun`'s,
and was at a large meeting the next day at Pilesgrove,
which I trust was a time of profit to Friends and others.
After this meeting I went to Solomon Lippincott`'s,
and the next day attended a large meeting at Upper Greenwich,
which was a time of hard labour, after which I came home,
being on the 26th day of the third month, 1766;
the Lord alone being worthy of all praise, glory and honour forevermore.
Some of the meetings in this journey were, I thought,
the largest in Pennsylvania and New Jersey,
that I had seen before in visiting those parts,
a great number of young people coming up on the stage of life,
who I wish may be an army for Christ.

In the same year and the sixth month, I visited Evesham, Chester and Rancocas meetings,
in the Jerseys, most of them being large, and attended with near unity with such as were,
I hope, honest-hearted towards God.
In the same month, a weighty concern attended Friends at our monthly meeting,
on account of a company of stage-players,
that came to the city in order to erect a theatre to exhibit their pernicious diversions;
to prevent which, and declare our testimony against their proceedings,
in a thing of so bad a tendency for corrupting the minds of the people,
leading them from the fear of the Lord into vanity--Friends agreed to address our governor,
John Penn, requesting him to interpose with his authority, to prevent the same.
He being then at Shrewsbury,
and Friends desirous to forward their address with
a view to the good of our city and people,
saw fit to appoint Mordecai Yarnall, John Pemberton, Joshua Emlen and myself,
to go to Shrewsbury, and present it to him,
it being about seventy miles from Philadelphia.
We accordingly proceeded, and discharged our message;
but the governor we found had given liberty and his promise to the players,
so that we had no prospect of obtaining redress from him;
yet I trust that Friends and we were clear in thus
discharging our duty to God and man in this respect.
I returned home on the 2nd of the month following, and enjoyed a degree of peace,
having some solid sittings in Friends families on our return,
and an opportunity of seeing some whom I valued in the Truth.

After these two journeys this year, I kept much at home, and in obedience to the Lord,
and in love to the inhabitants of this city, laboured in sincerity for their welfare.
In 1767 I attended the yearly meeting at Salem, which was very large,
and much favoured with a visitation of gospel love and power,
to the rejoicing the hearts of the faithful among Friends.

On my way to this meeting, I took the weekday meeting at Woodbury creek,
and on my return the youths`' meeting at Pilesgrove, which was large,
and both of them tending to solid satisfaction;
I had also some comfortable meetings in some families.

[.embedded-content-document.epistle]
--

[.letter-heading]
Epistle to Friends at their Quarterly Meeting at New Garden in North Carolina.

[.signed-section-context-open]
Philadelphia, Ninth month 21st, 1767.

[.salutation]
Dear Friends,

In true and brotherly love, I take this opportunity to salute you,
having been desirous, according to my measure,
that the Lord`'s glorious work and truth may prosper in your parts,
and prevail to the glory and honour of his most excellent name and praise,
that has planted a number of families, not many years since in that wilderness,
with a design I trust, that he "`might have a fruitful field or garden,
yielding pleasant fruits, and be a sweet savour to him.

And dear Friends, let the awful sense of the great care, tender mercy,
and good providence of God towards his flock and family be thankfully remembered,
so as to walk worthy of his grace and goodness towards you;
and let the love of God in Christ prevail in your hearts,
and brotherly love one towards another in the unity of the spirit,
which is the bond of peace;
that there may be no hurting or destroying in all the Lord`'s holy mountain;
but a care that you may be preserved in the faith and fellowship of the saints in light.
May you be as lights and way-marks to others,
ruling well in your places and stations in the church of Christ,
in the meekness and patience, humility and charity, as becomes the followers of the Lamb.
Look to him, the true guide of his flock, to be led in and out that you may find pasture,
and the best wisdom to direct your steps in the way of peace,
and establish your goings in righteousness;--that
you may be a peculiar people zealous of good works,
having a regard to Truth`'s honour, and true moderation in all things.
Live in the cross of Christ,
more than to mind temporal things or the profits of this world,--that
God`'s righteous seed may grow and thrive in all your minds,
to the bringing forth plentifully such fruits as best please him.
As you are willing to be one with the pure seed, and to suffer with it,
I hope you will enjoy the blessed promise of reigning with the same in the Lord`'s time,
and that all hurtful things that are like briars and thorns,
which would choke or hurt this precious seed, or sow discord among brethren,
may be watched and guarded against, so as not to allow of hardness of heart, prejudice,
or ill will one against another,
the nature of which is contrary to the heavenly peace
and sweet fellowship of Christ`'s kingdom,
that consists of peace and joy in the Holy Spirit.
And as I wish for the aged to keep their ranks in righteousness,
so I desire for the youth and rising generation,
that they may come up in the footsteps of the flock of Christ`'s companions,
and adhere to the true monitor and just witness of Truth in their own breasts,
living near to Christ, the Way, the Truth, and the Life,
that they may be a people to God`'s praise,
minding his early and tender visitations to their souls,
and the good advice and care of their godly parents and best friends;
and flee from youthful lusts and wantonness, wherein many go in the way to destruction,
and occasion great pain and affliction sometimes, to themselves and nearest friends,
when it is too late.

My prayers are for their lasting welfare and for you all;
and wish that brotherly love may rule and abound among you,
it being "`good and pleasant for brethren to dwell together in unity.
It is like the precious ointment upon the head, that ran down upon the beard,
even Aaron`'s beard, that went down to the skirts of his garments.
As the dew of Hermon, and as the dew that descended upon the mountains of Zion,
for there the Lord commanded the blessing, even life forevermore!`"
Psal.
cxxxiii.

In the love unfeigned, I conclude, and am your real friend,

[.signed-section-signature]
Daniel Stanton.

--

After this journey I was at several meetings in this province and New Jersey,
some of which were large and I hope beneficial to the well-minded;
one of them was at the burial of William Paxson, at Neshamony in Bucks county,
which was an awful solemn time, and a great gathering of people.
After these opportunities I stayed much in the city,
sincerely labouring for the prosperity of Truth in our own meeting,
with the faithful belonging to the same,
until I found a draft on my mind to visit some meetings in the Jerseys,
and the particular families of Friends belonging to Chester meeting,
a branch of Evesham monthly meeting.
I performed the visit in the twelfth month, 1768, in much love,
faithfully labouring both in the families where I went,
with my cousin John Lippincott and wife, Edmund Hollinshead, and John Roberts,
also in the several public meetings, which were large, and chiefly in Burlington county,
being eight in number, besides one with the Indians at Edgepelick, or Brotherton,
where divine strength was afforded to proclaim the council and will of God through Christ,
as I apprehended.
In the performance of this labour of love,
I enjoyed great comfort of mind and near unity with Friends,
my visits to whose families were generally opportunities of kind reception,
and such openness and brokenness of heart in many places,
that it bespoke a day of visitation of God`'s love to their souls,
and I wish it may be "`as bread cast on the waters,
that may be found after many days;`" Having performed this labour of love,
I visited several meetings in this province and New Jersey,
and attended the burials of some valuable Friends at distant places,
some of which opportunities were much to my satisfaction and solid comfort,
as were the beneficial and profitable seasons at home,
wherein I had to enjoy at times the Lord`'s living presence in the best of strength,
and divine liberty that is in the gospel, with my dear friends of our own meeting.

After this I found drawings of love in my mind towards Friends at Long Island and thereaway,
and having the concurrence and unity of my dear friends at our monthly meeting,
in the eighth month, 1769, I went forward, some Friends accompanying me.
The first night I lodged at Robert Collinson`'s,
and the next day attended the quarterly meeting at the Falls in Bucks county,
where was Rachel Wilson from England, and a very large meeting,
and I hope a time of profit to many.
I was also at their youths`' meeting the next day,
which was comfortably attended with the love of God, and with near unity with Friends.
After meeting dined at Mahlon Kirkbride`'s, then rode through Delaware ford,
and that day reached Samuel Worth`'s, and the next Joseph Shot well`'s,
and the day following being the first of the week, was at two meetings at Rahway,
with our friend Samuel Emlen, Jr., to some degree of satisfaction.

I then went with him and several other Friends to New York,
and engaged with him in visiting the families of Friends in that city,
which we performed to about forty families--attended
their monthly meeting to some degree of comfort,
and had several open times in places,
wherein I hope the Lord`'s precious seed was watered through his blessed presence.
My mind was much relieved of a burden that had lain upon me,
and having met with a kind reception among Friends there,
I went from there to Westbury on Long Island,
where we had a large meeting on the first-day of the week,
which was favoured with Divine help, living comfort and near unity with Friends.
Here came my kind companion Joshua Cresson,
whom I had left at Rahway when on our way to New York.
After this meeting we visited some Friends families, and the next day were at a burial,
and the day following at the youths`' meeting in the same place;
from which we went to Matinicook and Oyster Bay,
where were two large meetings to good satisfaction.

On our way to John Willis`'s, we called with several Friends to see Clements Willets,
who as I have already mentioned,
had been confined through infirmity of body between thirty and forty years,
and could not walk or stand alone, as I apprehended, most of that time.
We were owned together in waiting upon the Lord by his living presence,
and the dear afflicted Friend expressed,
that she did not know that she ever had a more satisfactory time,
and I hope it was a season of profit to several of us then present.
On the first-day following w`'e were again at Westbury meeting, which was large,
and I hope they were faithfully warned in gospel love, to the satisfaction of Friends.

From Long Island we crossed over the Sound into Connecticut, to a place called Middlesex,
in company with Matthew Franklin, John Wells, John Cock, Thomas Symonds and some others,
the distance being about twenty miles by water,
where was a small meeting under the name of Friends; a pretty many people came there,
who behaved soberly, and we were comforted together,
an openness appearing to receive the testimony of Truth.
The next day we had a solid time with a Friend who was weak in body, and in the family,
who seemed glad of the opportunity, receiving us kindly,
and some who did not make profession with us were extraordinarily so,
used us with much civility, and were helpful in assisting us to return to Long Island.
There we visited the following meetings: Bethpage, Westbury, Jacob Mott`'s,
the monthly meeting at Westbury; also had a large meeting at Jerusalem,
in which places I trust the Lord owned the labour of love bestowed among the people,
there being I thought great openness in the hearts of Friends,
and others not professing with us.
After these opportunities and having visited upwards of
fifty particular families belonging to Westbury meeting,
we parted with Friends in tender love,
and came with our kind friends and fellow-helpers
Matthew Franklin and John Willis to Cow-neck,
and had there a large and I hope a good meeting.
We went to our friend Phebe Dodge`'s who had crossed
the seas to England in the service of Truth;
we here met our friends Samuel Willis and wife, and several of their hopeful children,
and it being a time of comfort,
I was glad of our being together in that nearness of spirit,
wherein consists the best fellowship.

The next day we visited several Friends with Matthew Franklin, on our way to his house,
some of whom were confined through weakness of body, and I hope our calling to see them,
gave them some encouragement of mind,
through the Lord`'s tender mercy extended towards us.
Our next meetings were at Flushing and Newtown,
in which I hope I was clear as to religious labour among them;
after the last meeting I came away with several Friends and my companion,
peaceful in mind, to New York,
and the day and part of the night following got as far as Princeton in New Jersey,
and the next day reached home;
where I again found a kind reception from my beloved friends,
and the best of peace attending my mind;
the Lord alone being worthy of all the praise forevermore!

After my return home, deep and weighty labour fell to my lot in our meetings,
as at many other times among Friends in this city;
I also visited several who were weak in body, and some who were in deep affliction.
In the eleventh month this year, I attended Frankford, Fair-hill,
and Providence meetings, appointed by our worthy friend Rachel Wilson,
which were very large, and owned with a gospel visitation to the people.
After the last meeting our said dear friend went to Chester,
and the same day embarked on board a ship bound for London,
in order to return home with the well wishes and prayers, I believe, of a number,
for her preservation and safe arrival;
her faithful labours and diligent travels having given great
satisfaction to many Friends and other people in America.
From Chester in company with Joshua Cresson, I came that night to George Miller`'s,
and the next day went to Goshen monthly meeting,
which was a time of good satisfaction to my mind, and I believe to others.
We went on our way towards Concord quarterly meeting, which we attended,
and it was large and relieving to my mind, finding nearness of spirit among Friends;
also visited Birmingham meeting on the first-day,
and the general or youths`' meeting at Chester,
and had several solid opportunities in places in the families of Friends,
that both those meetings and the family visits,
were I believe to edification and comfort; Friends being kind and loving,
I returned home with a degree of peace in my own mind.

In the same month I went with my friend Israel Pemberton
to the first-day meeting at Byberry,
at which was Joseph White,
who in his public testimony was led to be remarkably particular,
as to the state of the meeting that day,
which I believe was wished by many that it might have its desired proper service;
the next day I came with my friend Israel to the monthly meeting at Abington,
through a great deal of rain, the meeting was small but something satisfactory.
On the seventh-day of the week following, I went into the Jerseys,
stopped that evening at Aquila Jones`'s and had a sitting in the family,
where was a number of slaves,
in which opportunity I found liberty to advise and
caution all present in much love and good will,
and I believe it was kindly received.

Next day I was at the meeting at Newtown in Gloucester county, at which were many people,
and to some good degree of satisfaction;
having for a number of years had a desire at times for the growth of Truth in that place,
I was made to rejoice of late,
that Friends had agreed for sometime past to hold a meeting there once a month,
the house being good, and many people living no great distance.
Although the meeting had been dropped for several years, I trust as it is again revived,
that if it be continued, the Lord through his tender and merciful visitation,
may be pleased to place his name among them.

In the course of my religious labours and travels,
a number have been reached unto by conviction,
and several convinced of the blessed Truth, as I have understood,
some of whom remained serviceable among Friends,
which I just mention as the Lord`'s blessing upon his own work,
who is worthy of all the praise, glory,
and honour forever!--I know I have endeavoured to serve Him in fear and trembling,
and frequently have been bowed under a sense of my great unworthiness;
but great has been his mercy and power,
extended towards me a poor tribulated sufferer in spirit, for the blessed seed`'s sake;
magnified be his eminent Name! he has hitherto been my rock, fortress, and deliverer,
and through his great kindness, I have a fixed hope in my mind of his salvation,
through Christ Jesus my dear redeemer,
whose glorious name be magnified and adored tor evermore!
