== Chapter VI

[.chapter-synopsis]
* Testimony of Daniel Stanton
* Testimony of Benjamin Trotter

[.embedded-content-document.testimony]
--

[.letter-heading]
The Testimony of the monthly meeting of Friends in Philadelphia,
concerning our dearly beloved friend, Daniel Stanton.

When John the divine was in exile in the isle of Patmos, he heard a voice from heaven,
saying,
'`Write,--Blessed are the dead, who die in the Lord, from henceforth, yes says the spirit,
that they may rest from their labours,
and their works do follow them;`" which we believe
now is the portion of our worthy friend,
concerning whose faithful services we are engaged
from the united motives of love and duty,
to give this testimony; desiring that all who read it, and more especially the youth,
may be excited by his example, to seek an early acquaintance with the Lord,
and to take up their daily cross in the prime of their days.
Thus, they also, may become shining lights and instruments of good to others.

He was born in this city, in the year 1708, and his father dying before his birth,
and his mother a few years after, he suffered great trials and hardships when very young.
Being early concerned to seek the knowledge of God,
he had a fervent desire to attend religious meetings,
though subjected to many difficulties and discouragements,
before that privilege was allowed him; yet,
being earnest in his desires to obtain divine favour,
he was eminently supported under great conflicts and probations,
and continuing faithful to the degrees of light and grace communicated,
a dispensation of the gospel ministry was committed to him,
sometime before the term of his apprenticeship was expired;
and abiding under the sanctifying power of Truth, he grew in his gift,
and became a zealous faithful minister.

He was very exemplary in his industry and diligence,
in labouring faithfully at his trade, to provide for his own support,
and after he married, and had children, for their maintenance;
and was often concerned to advise others to the same necessary care;
yet he continued fervent in spirit for the promotion of Truth and righteousness,
so that he was soon engaged to leave home and the nearest connections of nature,
to publish the glad tidings of the gospel,
and frequently visited most of the meetings of Friends in this and the adjacent provinces,
and several times as far as the eastern parts of New England.
Having thus honestly discharged his duty among us above twenty years,
and feeling his mind constrained in the love of the gospel,
to visit the few Friends who remained in some of the West India Islands,
and from there the meetings of Friends in general through Great Britain and Ireland,
he communicated his concern to a few of his most intimate friends,
who having unity therewith, he was encouraged to lay it before our monthly meeting.
Before he entered on this weighty service,
he passed through a near trial and affliction in the death of his beloved wife;
under which exercise he was graciously supported by the arm of Divine strength,
which had often been revealed for his help,
in times of inward conflicts and outward distresses.

His concern to travel in the service of Truth continuing,
and the meeting having full unity with him therein, he embarked in the fifth month, 1748,
accompanied by our dear friend, Samuel Nottingham, in a vessel bound for Barbados,
and having visited the few meetings in that island,
they went by way of Antigua to Tortola, where they continued some time,
having some difficulty to get a passage to Europe;
and their voyage there was attended with some singular hazards and dangers,
which occasioned their landing in Ireland; where our friend Daniel continued some months,
visiting the meetings of Friends in that kingdom; and after he apprehended himself clear,
went over to England, and visited the meetings generally in that nation,
and in Wales and Scotland, where his meek, circumspect conduct and conversation,
and lively edifying ministry, rendered his visit very acceptable,
and his memory precious.

In his return home, and for some time after, he was in a low afflicted state of mind;
being apprehensive, that through diffidence,
and the lack of perfect resignation to the Divine will,
he had omitted fully performing the service required of him,
by not visiting the few Friends in Holland: yet he was mercifully preserved,
and after a time of deep exercise,
raised again to sing of the mercies and lovingkindness of God on the banks of deliverance.

He several times, with other Friends appointed to that service,
visited the families of Friends in this city; and between the years 1757 and 1760,
being accompanied by our friend John Pemberton,
he visited the families of Friends generally within the limits of our meeting;
which weighty exercising service,
he was enabled to perform to our edification and satisfaction.
After which,
he was frequently engaged to excite Friends to this useful and edifying practice.

In the twelfth month, 1760,
he set out on a visit to the meetings in the western parts of this province,
and from there in Maryland, Virginia, and North and South Carolina,
and returned in the sixth month following;
since which he frequently visited many of the meetings near home,
and some as far as Long island, and other parts of the province of New York.
Within the last two years,
he visited the families of Friends of some of the meetings in West Jersey,
in the city of New York, and part of Long island; and after his return from this service,
with great peace and satisfaction,
he expressed his apprehension that he was now clear of all places,
and that his stay here was near over; having an evidence,
that he had been faithfully concerned from his youth to fear and serve God.

His chief labour and religious exercises were in this city,
where he was a diligent attender of all our meetings,
and often on committees appointed on the services of the church;
in which he was solid and weighty in spirit, waiting for the springing up of life,
being steadily concerned both in and out of meetings, to live near the divine fountain.
Thus he was very frequently qualified, and enabled to stir up the pure mind,
and to recount the gracious dealings of God to mankind,
and as a faithful ambassador to warn the negligent to flee from the wrath to come,
and to excite the people to bring forth fruits answerable
to the great mercies graciously bestowed on us;
and was sometimes constrained to declare in a prophetic manner, a day of trial,
in several instances, very shortly before such a season came to pass.

He was of late deeply exercised in consideration of the evils of the horse races,
stage plays, drunkenness,
and other gross enormities encouraged and increasing in this city;
closely exhorting our youth against those pernicious
and destructive devices of the enemy of mankind;
and under the awful sense that God will judge and punish the wicked and evil doers,
he was often fervent in public supplications,
that the Lord would lengthen out the day of his merciful visitation,
and yet try the people longer; which seasons were solemn and humblingly affecting;
manifesting, that although he was very close and sharp in reproof against evil,
yet most tenderly concerned,
that the transgressors of the righteous law of God might be prevailed with to repent,
return, and live.

His love for the rising generation was very great;
which he manifested by his affectionate notice of them,
and especially of those who were religiously inclined,
and his house was open to receive such, his conduct with them being seasoned with grace,
and his counsel instructive and helpful to those
who had seeking desires after the knowledge of Truth,
often lovingly inviting them to come, taste and see, that the Lord is good;
greatly desiring, that all who profess the Truth,
might walk agreeable to its dictates and be led thereby, as our worthy predecessors were,
into that meekness, humility, and godly simplicity and plainness,
which rendered them conspicuous and shining examples,
and that none might rest short of the enjoyment of the life of religion,
his zeal being great against such who have the form of godliness,
and by their actions manifest they have not the power thereof;
and he often fervently advised and cautioned those who are eagerly pursuing the world,
and by the surfeiting cares, and grasping after earthly treasures,
frustrate the good purpose of the visitation of divine grace to them;
and closely reminded those, who in their small beginnings were low and humble,
that now they were abundantly favoured,
they should not set their affections on things below,
but remember the Rock from which they were hewn;
and his concern was great that those who had the glad tidings of the gospel to publish,
might be true examples to the flock,
and adorn the doctrine they had to deliver by a circumspect life and conduct;
and where any by not steadily keeping to that which would have preserved them,
had involved themselves in difficulties,
either by letting their minds out to the gains and profits of this world, or otherwise,
his travail was great for such that they might be brought through,
and every cloud and mist removed.

He was much employed in visiting the sick and afflicted,
to whom he administered spiritual advice and experience,
and often engaged in humble prayer for their support;
and in the distributing to the necessitous according to his circumstances,
he manifested his benevolent disposition.

As he had been many years under great exercise and suffering
of spirit on account of the slavery of the poor Africans,
and frequently bore testimony against that unrighteous gain of oppression,
he was of late somewhat relieved,
as he found the eyes of the people become more open to see the iniquity of the practice;
and he died in faith, that the light of the gospel will so generally prevail,
that the professors of Christianity will find it their duty
to restore to these people their natural right to liberty,
and to instruct them in the principles of the Christian religion.

On the 5th day of the fifth month, he was violently seized with the bilious cholic,
and continued in great pain several days; but afterwards being somewhat easier,
he was at our morning and evening meetings on first-day, the 13th of the month,
in which he was much favoured in his public ministry,
and expressed that he thought his time would not be long with us.
After this day`'s labour, he was again confined,
yet being a little recovered he was at our meeting on fifth-day, the 24th of the month,
which being small, he expressed his sorrow for it,
and encouraged Friends to diligence in the attendance of week-day meetings,
the benefit of a faithful discharge of duty therein being great;
the next day he was at our monthly meeting,
and to his own and our admiration was enabled to stay through both our sittings,
though the last of them was longer than usual,
and he afterwards expressed that he thought himself better in the
meeting than when out;--it was a season of divine favour,
and some weighty matters being before the meeting,
he with great openness spoke pertinently and clearly to them,
encouraging Friends to the supporting and maintaining our Christian testimony,
against all that is contrary to it; this was the last public meeting he was at,
being the next morning early seized with a renewed attack of the same disorder,
which increased on him several days, and was so fixed,
that all the endeavours of several skilful physicians and tender nurses,
were not effectual to remove it, though in some measure to mitigate the pain,
that he suffered much, not being able to lie down in his bed several weeks,
yet through all he was mercifully supported, in much resignation and patience,
rather inclining, if it was the Lord`'s will, to be released.

For two or three weeks before his sickness,
he appeared very desirous of settling everything
he had to do respecting the affairs of this life,
and desired a Friend to review and transcribe the short
memoirs he has left of his travels and religious services,
and to write his will, which he executed the day before he was first taken sick,
and then appeared easy in his mind.

During the time of his sickness he often expressed his concern
lest his friends should be too anxious for his recovery,
saying, if he should live longer,
and through any human frailty or infirmity occasion any reproach,
it would be a cause of sorrow to them.

By the desire of his friends who attended him, he rode out several times,
though not without much difficulty,
and spent the last two days of his life at the houses of two of his intimate friends.
As he drew near his end, the strength of his love to mankind in general,
and his friends in particular, evidently increased,
much desiring the prosperity of Truth;
and when a meeting time came had an earnest desire to be with Friends,
and particularly the day before his departure.

During his sickness, he frequently expressed himself in a very seasonable, instructive,
and affecting manner; and the evening of the first-day before he died,
several Friends coming in to see him, he spoke a considerable time to them,
having before been desirous of such an opportunity of the company of his friends,
to sit down and wait upon God, which was his great delight.

The last of his life he spent at the house of his friend Israel Pemberton, at Germantown,
and was unusually free and cheerful, even till ten o`'clock at night,
when he undressed himself, and went into bed, remarking on lying down,
that he had not before been able to do so, for five weeks or upwards;
and he soon after fell asleep,
but in a short time was awakened by the return of pain and difficulty of breathing,
which through his illness he had been much afflicted with,
so that he was obliged to set up in bed, and thus continued,
at intervals freely conversing with our said friend, who sat up with him;
and he expressed his great thankfulness that his head was
preserved free from pain and his understanding clear,
and that though it had been a time of close trial and deep probation,
he could say he felt the evidence of divine support still to attend him.--After which,
his pains increasing, he got up and dressed himself, and walking about the room sometime,
sat down in an easy chair, in which he fell into a sweet sleep,
and in about three hours departed without sigh or groan.

Thus died this righteous man, who having fought the good fight and kept the faith,
finished his course in full unity with us,
and universally beloved by his fellow citizens, on the 28th day of the sixth month, 1770,
in the 62nd year of his age, and the 43rd of his ministry.
His body was the next day attended by a large number of people
of various religious denominations to our meeting house,
and afterwards interred in Friends burial ground in this city.

[.signed-section-context-close]
Signed on behalf, and by appointment of our monthly meeting, held in Philadelphia,
by adjournment, the 2nd of the eighth month 1770.

[.signed-section-signature]
James Pemberton, Clerk.

--

[.asterism]
'''

There being no other written memorial of our friend Benjamin Trotter,
between whom and Daniel Stanton, a long uninterrupted friendship subsisted,
it is thought the subjoining the following here, may be acceptable to Friends in general.

[.embedded-content-document.testimony]
--

[.letter-heading]
The Testimony of the monthly meeting of Friends in Philadelphia,
concerning our beloved friend and brother, Benjamin Trotter, who was born in this city,
in the ninth month of the year, 1699.

He was one whom the Lord early visited,
and reached unto by the reproofs of his Divine light and grace,
for those youthful vanities and corrupt conduct,
which by nature he was prone to and pursued, to the grief of his pious mother,
who was religiously concerned to restrain him;
but as he became obedient to the renewed visitations of the heavenly call,
denying himself of those things he was reproved for,
he not only learned to cease from doing evil, but to live in the practice of doing well;
and continuing faithful, became an example of plainness and self-denial,
for which he suffered much scoffing and mocking of
those who had been his companions in folly;
yet he neither fainted nor was turned aside by the reproaches of the ungodly,
which thus fell to his lot, for his plain testimony against their evil conduct.

In the twenty-sixth year of his age, he appeared in the work of the ministry,
and laboured therein in much plainness and godly sincerity,
adorning the doctrine he preached, by a humble circumspect life and conduct,
being exemplary in his diligence and industry to labour honestly for a livelihood,
though often in much bodily infirmity and weakness, desiring, as he sometimes expressed,
that he might owe no man anything but love.
His inoffensive openness and affability,
drawing many of different denominations to converse with him,
he had some seasonable opportunities of admonishing
and rebuking the evil doer and evil speaker,
which he did, in the plainness of an upright zeal for the promotion of piety and virtue,
tempered with true brotherly kindness and charity;
respecting not the person of the proud nor of the rich, because of his riches,
but with Christian freedom, declaring the truth to his neighbour,
and was thus in private as well as public, a preacher of righteousness.

In his public ministry he was zealous against errors both in principle and practice,
and constantly concerned to press the necessity of
obedience to the principle of divine grace;
a manifestation of which is given to every man; knowing from his own experience,
that it brings salvation to all them that obey and follow its teachings,
and was frequently enabled with energy and power to bear
testimony to the outward coming of our Lord Jesus Christ,
his miraculous birth, his holy example in his life and precepts,
and his death and sufferings at Jerusalem,
by which he has obtained eternal redemption for us.

In his public testimony a little before his last sickness,
he expressed his apprehensions, that his time among us would be short,
and fervently exhorted to watchfulness and care, to keep our lamps trimmed,
and our lights burning, and urged the necessity of being prepared to meet the bridegroom,
as not knowing at what hour he will come.

He travelled several times,
and visited most of the meetings of Friends in this province and New Jersey,
and some in the adjacent provinces, but was not much from home;
being upwards of forty years a diligent attender of our religious meetings in this city,
zealously concerned for the maintaining our Christian
discipline in meekness and true charity,
careful in the exercise of that part of pure religion,
visiting the widow and fatherless in their afflictions,
and often qualified to administer relief and consolation to their dejected minds.

Afflictions of various kinds, and some very deep and exercising,
fell to his lot through the course of his life,
which he was enabled to bear with exemplary patience and resignation,
and particularly through his last illness, in which, for upwards of six weeks,
he underwent great difficulty and pain, being afflicted with the asthma and dropsy,
so that he suffered much, yet was never heard to utter a murmur or complaint,
but frequently expressed his thankfulness, that he had not more pain,
and often engaged in prayer, that he might be preserved in patience to the end,
which was graciously granted him;
so that he was capable of speaking to the comfort
and edification of those who visited him;
and from the fervent love of the brethren, which evidently appeared through his life,
and most conspicuously during his last illness, and even in the hour of his death,
we have a well-grounded assurance that he is passed unto life,
and has received the reward of the righteous.

His body was attended by a great number of Friends and others,
his fellow-citizens of various religious denominations,
to our meeting-house in High-street, on the 24th of the third month, 1768,
and after a solemn meeting, in which several living testimonies were borne,
was interred in our burial ground in this city.

[.signed-section-context-close]
Signed on behalf, and by appointment of our monthly meeting, held in Philadelphia,
by adjournment, the 4th day of the eighth month, 1769.

[.signed-section-signature]
James Pemberton, Clerk.

--
