[quote.epigraph, , Mal. 2:5]
____
My covenant was with him of life and peace, and I gave them to him,
for the fear wherewith he feared me, and was afraid before my name.
____

[quote.epigraph, , Heb. 11:4]
____
He being dead, yet speaketh.
____

== Chapter I

[.chapter-synopsis]
* His birth and parentage
* Apprenticeship
* First coming forth in the ministry
* First journey to Rhode Island
* His marriage and second journey to New England, etc.

In a grateful sense of the many helps and great goodness of the Almighty to my soul,
whereby he has been pleased from my young years to
incline my heart to fear and serve him,
it is on my mind to leave some account of my life, travels and experience;
wishing it may be a means to stir up the pure mind in any, to obey the will of the Lord,
and to serve him, while they have time and opportunity to perform the same;
for he is worthy to be had in everlasting remembrance,
and is a good rewarder of all the sincere in heart.
Although they may have tribulations on the earth,
they have also the company of Christ our dear Redeemer,
who promised to be with his disciples to the end of the world.

By the account I have had, I was born in the year 1708, in Philadelphia,
in the province of Pennsylvania, of honest parents, Daniel and Abigail Stanton,
and it was my hard lot soon to be deprived of them both; my father I never saw,
he being lost at sea sometime before I was born; and my mother died when I was a child,
so that I have but little remembrance of her.

After her death, I met with great hardships, both of body and mind,
being destitute of parents, and of brother or sister, that I was in a lonely state,
and went to live at several places a short time, the last of which,
before I was put apprentice, was in New Jersey, with my mother`'s brother;
during which time I went through great difficulties.

I lived there several years,
and had no opportunity to go to any place of religious worship;
but the Lord was pleased by his grace and good visitation, to operate on my mind,
so that I was made to dread and fear the great Almighty Being;
and it was given me to know, that "`God is a spirit, and they who worship him,
must worship him in spirit and in truth.`"
Through the blessed knowledge of God by his holy Spirit,
I had great reproof in my own breast for sin and transgression,
and dreaded to speak bad words, or to do what was evil,
and was brought by inward conviction to mourn, and seek for mercy for my soul.
At a time when I heard of the suffering of my dear Saviour on the cross,
and how he suffered unto death, my heart was broken before the Lord,
and I went alone and wept,
being much affected with a sense of his suffering by that hard-hearted people, the Jews,
and of his being crucified.
Great was the goodness of the Almighty to me,
in giving me a sense of many things appertaining to godliness,
in the time of this tender visitation.
I found by the divine witness in myself, that if I would be a disciple of Christ,
I must take up my cross daily, to that which displeaseth God;
he being greatly to be feared and obeyed,
and was worthy of the deepest reverence that my soul,
body and strength could ascribe to his all powerful name.

Although it was hard to the natural part to become
slain to the recreations and pleasures of this life,
fervent were my cries and seeking after the ways of the Lord,
and I thought much of eternity in another world.

I had heard of many forms of worship,
but had no opportunity to be with the people for that service to God,
which was a great trouble to my mind;
but at one time I asked leave to go and see a relation,
with an intention for him to show me the way to the meeting of Friends,
which was held at Newtown, in Gloucester county.
He was loath to take the pains to accompany me, not knowing the solid desire of my mind;
but through persuasion, I prevailed with him to go with me to the meeting,
where I was more desirous to get some good, than to be seen of men.
We sat in a part of the meeting together,
where we were not much noticed by any that I know of, and in this blessed opportunity,
through the power of truth, and the good testimony of that dear servant of Christ,
John Estaugh, being attended with the authority of the Word of life,
my heart was greatly contrited and my spirit baptized in the presence of God.
It was a joyful day of good tidings to my poor seeking soul,
and the eminent and powerful advice,
that did attend that worthy instrument in the Lord`'s hand for my salvation,
has been like "`bread cast upon the waters, that has been found after many days.`"

I went from that meeting much satisfied with the way of worship of Friends,
and continued earnest in spirit,
that I might have further knowledge of the blessed Truth.
My inward exercises were a great deal of sorrow and mourning,
that I might come forward in the work of religion,
and do that which is right in the sight of God.

Living with my uncle till near the age of sixteen years, I became uneasy,
being desirous to learn a trade,
not knowing what I might have to depend on for a livelihood,
more than the labour of my hands; although my mother left considerable at her death,
under the care of those who she expected would do justly by me; but it proved otherwise,
they depriving me of the whole, to a small matter, less than twenty pounds.
I went on trial to a ship carpenter in Philadelphia, in condescension to my uncle,
it being a trade he rather chose for me, than I did for myself, and was there sometime,
though I was soon dissatisfied,
both with the trade and on account of the wicked conversation of the people of the yard,
who being very vain, were a great exercise to my mind.
My master and mistress were kind and friendly to me, which was some comfort;
but the greatest satisfaction I had in this world,
was that I could attend religious meetings on the first-day of the week.
I was often favoured to hear the truth declared in
the demonstration of the spirit and power,
as also with a secret divine power at work in my heart,
which afforded solid pleasure and profit, in the midst of my trials.
For being soberly inclined, and delighting to attend religious meetings,
I met with scoffings and mockings,
and some in an outrage would bid me go along to meeting,
despising my diligence on that account; but I was enabled through mercy and grace,
to bear revilings as well as many deep distresses, which fell to my lot;
being much concerned to seek after the kingdom of God, and his righteousness.
Oh, the inward travail that I underwent, none knew but the Lord!
At an evening meeting near where I sat, a little way from the door, Benjamin Kidd,
from England, a Friend in the ministry, then on a visit to this province,
came in and sat just by me, and in the meeting was eminently favoured in prayer,
which I have many times thought was a particular instance of divine mercy to me,
in so deep a travail of soul and spirit,
as I had to wade through in several respects at that time.

After being some time at the ship carpenters`' trade, which was not agreeable to me,
I went again to my uncle`'s, where a Friend from Philadelphia came,
who having seen me when I lived in town, would have me to go apprentice to him,
he being a joiner; which I accordingly did,
believing it would be of good service for me to have a trade to depend on.
I served with him until I was about the age of twenty-two years;
and in the time of my apprenticeship,
the goodness of the Almighty was great in preserving me through my tribulations,
which were various, beyond my setting forth.
But the pure love and fear of the Lord, accompanied my spirit,
and through the divine appearance of light and grace,
I was led in a close walking before him.
My understanding was opened to have a sight of the many things,
which the Spirit of Truth leads into; some whereof were plainness in speech and clothing,
few words in conversation, watchfulness and prayer, choosing rather to be alone,
than in the company of those whose discourse and talking were out of the fear of God.

I much delighted in retirement,
and often walked alone and poured out my complaints before the All-seeing eye,
that knew the condition of my heart,
desiring that he would be pleased "`to create in me a clean heart,
and to renew a right spirit within me.`"
I wanted to know the work of reformation effectually carried on,
according to the mind and will of the blessed Truth,
and the nearer I kept to what it made manifest,
the greater strength and dominion was given me to overcome the defilements of the world;
and a concern came upon me in observing the pride and vain glory of the times.
I had very few acquaintance, and was rather despised and derided by some,
who overlooked the just Witness of Grace in themselves.

"`I chose rather to suffer affliction with the people of God,
than to enjoy the pleasures of sin, for a season.`"
"`The sufferings of this present time worketh for us,`" as the apostle saith,
"`a far more exceeding and eternal weight of glory;`" and the blessed peace,
that our dear Lord gives to those who follow him whilst here,
is a reward sufficient to the sincere in heart, to hold out to the end.

The countenance and good example of faithful Friends had a great reach on my mind.
When I came to be more acquainted with the dealings of the Lord,
and could get frequently to religious meetings, and beheld the sitting of his servants,
and attendance of his ministers, I could say, as did the queen of the South,
who came from far to see the wisdom of Solomon, that the one half had not been told me,
and one greater than Solomon was in the midst of his people.
Praised be his great name, even the name of Christ our dear Lord,
that greatly appeared in power and majesty in Zion in those days,
to the tendering my heart and spirit before him time after time,
and not only eminently visited my soul, by his glorious light and truth,
but sent many servants among us, from far and near, filled with gospel rain,
to the watering the heritage of God; and the Lord, the master of our assemblies,
was pleased to fasten their testimonies as nails in a sure place.

After many powerful seasons of divine grace,
being favoured to see the goodness of the Lord in the land of the living,
as also "`to taste and handle of the good word of life,`" a great
concern of soul came upon me to open my mouth in a public manner,
for the cause of religion, and the prosperity of Zion,
which was a great and weighty work for me to engage in.
Being one of the meanest in this world, as I thought, and an apprentice lad,
reasons would arise in me against so great a duty,
not knowing how I might be used by my master,
and whether it might agree with the unity of Friends,
they being a great and wise people in this city, and by their knowledge and experience,
were gifted with a sight of spiritual things, beyond my low capacity,
as well as zealous for the good cause of God in their day.
I waded for a considerable time through much trouble and sorrow of spirit,
lest I should go too fast, or before my divine Guide,
for they who go before they are sent, cannot profit the people,
or have peace in themselves, and peace to me and to do the will of the Lord,
was what I most desired.
Oh! the earnest prayers that were in my heart that
I might be rightly directed in all things,
to the honour and praise of my blessed Lord and master.
A degree of his mighty power would lay such constraints upon me,
that for Zion`'s sake I could not rest,
and for Jerusalem`'s sake I could not hold my peace;
so that after many powerful influences of the divine Word,
at about the age of twenty years, I appeared in a few words in prayer,
at an evening meeting at Philadelphia, and after this,
sometimes in a few words by way of testimony, as they were put in my heart,
in a great deal of fear and dread of the Almighty Being.
Friends bore with my appearance with much tenderness,
and the ministry of those who were largely gifted in the mysteries of the kingdom,
and like scribes well instructed thereto,
that could bring out of the treasury things new and old,
would correspond with what I had to say in the fear of the Lord; which blessed helps,
together with the evidence of peace in my own breast, gave a confirmation to my mind,
that I was in the way of my duty.

After I came forth in this laborious exercise, I dreamed a dream, or saw in a vision,
that I was, as a little child born into the world, and my mother was very tender of me,
who I have thought to be the church; and there was an enemy that sought my life,
as though he would destroy me, but she that was my mother made her escape,
and carried me into the wilderness, and we were preserved.
At another time when I was much concerned in spirit for acceptance with the Lord,
I dreamed that I was travelling in a path, in which I met with some difficulties,
but got through them and met with death; a man came with a book,
and it was said that my soul was acceptable with the Lord.
I have had great cause to speak well of his excellent
name for the revealing his secrets to my understanding,
as I kept in his holy fear.

About the time that I first appeared in words in the congregations of the Lord`'s people,
and sometime before, the glorious day spring from on high powerfully appeared amongst us,
and several were engaged to speak to the praise of the Almighty,
and to bear testimony to his great and good name; three before I appeared,
and two afterwards; the first were Mary Nicholls, Benjamin Trotter, and Mary Emlen,
the next were Joyce Marriot and Elizabeth Widdifield,
who continued serviceable ministers among Friends.
I thought it might be said to be a time in some measure
of the fulfilling the prophecy of the prophet Joel,
"`I will pour out of my spirit upon all flesh;
and your sons and your daughters shall prophesy, your old men shall dream dreams,
your young men shall see visions;
and also upon the servants and upon the handmaids in
those days will I pour out my spirit.`" Joel 2:28-30.
The plainness, zeal, and pious example of many Friends in those days,
made them as lights in this city, and instructors to me to follow them,
as they followed Christ; and as I kept inward before the Lord in his fear,
he was pleased to reveal his blessed mind and will,
in things concerning the Gospel ministry,
which is not to be received from man nor in the will of man;
but by the revelation of Jesus Christ.
As I grew in the gift communicated to me,
he was pleased to give me an open door in the hearts of his people;
praised be his name forever more!
Sometimes I had drawings in my mind to go to a neighbouring meeting,
and what I had to say in their hearing was well received.

After I had served out my apprenticeship, I wrought journey-work,
and lived with my master until his death, which was soon after I was free,
and then wrought with another Friend in the city some time.
Having an opportunity to go to Rhode Island, the place where my father was born,
and several of his relations living there, I was desirous to see them,
having an account of some estate that was my father`'s, laying in that country.
On this account, and to see my relations and friends, I took a journey in the year 1731,
with Henry Frankland, from old England, who came to America, on the service of Truth,
and being about going to those parts, was so kind as to take my company.
He was a solid exemplary worthy Friend,
whose ministry and gospel labour was to edification among Friends.
My undertaking this journey was laid before our monthly meeting,
and Friends were pleased to give me a certificate.

The first meeting we went to, was at Burlington,
and from thence to several others in New Jersey, as Little-Egg-Harbour, Manesquan,
Shrewsbury and Woodbridge, and so to New York, to meetings on the main,
the yearly meeting at Flushing,
and to Friends`' meetings pretty generally on Long Island;
several of which were much to satisfaction and comfort.
I was glad to see and find the near unity that was among Friends, where our lot was cast.

From this Island we went through Connecticut, which was a baptizing time to me,
being a young traveller, not much acquainted with the difference of places,
and behaviour of people from home.
Their conversation, also their principles, through that government,
being greatly different from Friends; and although high in profession of religion,
they seemed to me very little acquainted with the Light and Spirit of Christ.
It was a dark time, in which I went through much deep inward suffering.
We passed along until we got to Kingstown, near Rhode Island, where we had a meeting,
and then had one on Connanicut, and attended the yearly meeting at Newport, Rhode Island,
which was very large, and I hope a good meeting to a solid remnant.
My friend Henry Frankland, whom I accompanied thus far,
proceeded on his journey to visit Friends in New-England,
and I stayed in order to get my outward affairs settled,
and to visit several Friends on that Island.
One was, that dear and worthy Friend Jacob Mott,
whose countenance shined and appeared as a follower and servant of Christ;
it did me good to see him, and when I took my leave of him,
his solid advice to me made lasting impressions on my mind.

After I had stayed some time at this place, and had seen my relations and friends,
I returned to Philadelphia, where I had known in an extraordinary manner,
the gracious dealings of the Almighty;
and I endeavoured to seek counsel of him to know
where I had best settle myself in the world.
It seemed most suitable for me to continue in this city,
where I wrought journey-work at my trade some time; after which I rented a shop,
and sat up for myself, humbly desiring of the Lord to add his blessing to my endeavours;
not that I craved great things,
but that by an honest industrious care I might have what was needful,
as food and raiment, and desired "`to do justly, love mercy, and walk humbly with God.`"
And the abundant mercies and blessings wherewith
he was graciously pleased to make way for me,
both in things spiritual and temporal, were and are gratefully to be remembered by me,
his goodness and peace being as a stream of living water to my soul,
when favoured to drink thereat.

I wrought hard at my outward calling when at home,
yet not so much confined but that I kept close to religious meetings;
in which the good presence of Christ our dear Lord, would many times overshadow them,
and I have had to sit under the shadow thereof with great delight.
After such precious meetings with his people,
I found my mind better qualified to attend to my
necessary business and the affairs of life.
When the motions of truth would spring in my heart to visit religious
meetings in places adjacent in Pennsylvania and New Jersey,
I freely gave up to go to them, and sincerely laboured therein in the love of truth,
in which I found great satisfaction, and with many Friends,
the unity of the Spirit in the bond of peace,
I hope in places my labour was of some service;
the praise of which I freely attribute to my great Lord and Master Jesus Christ;
blessed be his holy name!
He sustained and supported me,
and through his gifts and grace preserved me in the fear of God;
his fear was a fountain of life,
as well as unspeakable pleasure in my first setting out in the world for myself.

Oh! the streams of the celestial fountain or waters
of life stand open to all that are athirst,
that they may drink; and they may have wine and milk without money and without price.
I wish that there was a more general thirst in the children of men,
to drink of this water, which Christ our Lord has promised to give to true believers,
and that it should be in them a well of water springing up into everlasting life;
and he has said of himself, "`I am the living bread which came down from heaven,
if any man eat of this bread he shall live forever.`" John 6:51.
How great is his goodness and condescension to hungering and thirsting souls!
Thanks to him forever more, they that eat of this living bread,
partake of the blessed communion, and know the supper of the Lord;
they sensibly partake of the new wine of the kingdom;
they are like new bottles filled with new wine,
and know him to drink and sup with them of this wine,
new in his heavenly Father`'s kingdom.
I take those to be new bottles that are created anew in Christ Jesus unto good works,
and that know the kingdom of our heavenly Father to be come,
and his will to be done on earth as it is done in heaven.
As we are taught to pray for this,
it would be well for all mankind to come to the experience of it in themselves;
for Christ our Lord said to some of old,
"`The kingdom of heaven is within you;`" and the faithful
have it in their experience to be the same now.
It is a kingdom that consists of peace and joy,
to the faithful subjects of his holy reign and government.

[.small-break]
'''

In the year 1732,
I found freedom in my mind to accompany my uncle Thomas Chalkley to visit
some of the meetings of Friends in Bucks county and New Jersey,
and afterwards Chester county;
in the performance of which we had near fellowship together; Friends were kind,
and I believe glad to see us; several of those meetings were large,
and I hope comfortable to many.
He was a near fellow-helper to me in my religious labours for the promotion of truth,
and a bright example in the meekness and patience of the Lamb.
I do not know that I was ever acquainted with a man more inward,
whose heart seemed to be more placed upon heavenly treasure,
both in meetings and out of them, than this dear disciple of Christ.

When these visits were accomplished,
I having been engaged on account of marriage to Sarah Lloyd,
a virtuous young woman who feared the Lord, daughter of honest parents,
John and Sarah Lloyd of this city, on the fifth day of the second month, 1733,
we accomplished that weighty undertaking in the pure fear of the Lord,
in near affection to each other, and with the unity of Friends.
After I was agreeably settled, my heart was still given up to go of the Lord`'s errands,
as he was pleased to send me; and I visited Friends in these two provinces,
Pennsylvania and New Jersey, and other places,
as the motion of life engaged me from place to place;
in a short time after I went as far as Shrewsbury, and some meetings thereaways.

[.small-break]
'''

In the year 1734, I visited the meetings of Friends at Salem, Alloways Creek, Greenwich,
Cape May and Great-Egg-Harbour, several of which were to satisfaction and comfort.

[.small-break]
'''

In the year 1735, having a concern on my mind to visit Friends in New-England,
and our monthly-meeting in this city giving me a certificate of their concurrence therewith,
I accordingly proceeded, and was at several meetings in the Jerseys;
from thence I went to the yearly meeting at Flushing, on Long Island;
where was our friend Joseph Gill from Ireland, and several from Pennsylvania;
the meetings were large, and religious labour was bestowed among the people.
After it I visited Friends generally on that Island,
many of the meetings being very large and comfortable,
attended I trust with the blessed power and presence of the Lord,
which begat great nearness in the best fellowship with the tender-minded.
I then proceeded to meetings on the main, as West Chester, Mamaroneck, Rye,
and several others; some of which were large and solid.

After being at some meetings in Connecticut, I went forward to Rhode Island,
which was a wearisome travel.
I got to Newport, and met with a kind reception from Friends,
whom I visited in much love,
there being a great number who make a profession of the way of truth;
I was glad to see them,
and could have been more so that all lived in possession of the same.
From Rhode Island I took meetings in my way to Nantucket,
where on my arriving I was kindly taken home by Nathaniel Starbuck,
whose heart and house were open to receive the messengers of Christ.
On this Island I met with a great number of choice exemplary Friends,
and had several meetings among them, which I believe tended to edification.
Being clear of this place, I returned to the main, and taking meetings in my way,
came to Boston, where I spent some time with Friends,
both in public meetings and in their families;
they being loving to me and glad of being visited.
Their number was small in the whole,
but they seemed to be well treated by people of other persuasions,
far different from what it was in the early visits of Friends in that place,
in which some of the servants of the Most High suffered unto death.
From Boston I went to Lynn, Salem, and Newberry, and had comfortable meetings,
as also at another place between Newberry and Dover.

After I had seen Friends at Dover and Cachechy, and had a meeting near Dover,
I returned to Salem and Lynn,
and stayed some time at my kind friend Zaccheus Collins`'s.
Having met with some disappointment in travelling,
which detained me some weeks, I constantly attended meetings at Lynn,
and found great openness and unity with Friends there,
and believe my stay tended to some service,
for the promoting of near love among the little flock of Christ in that place,
having many blessed opportunities among them.
I also went to the yearly meeting at Boston, and back to the yearly meeting at Lynn;
which was large and greatly favoured with the ministry
and service of that worthy handmaid of the Lord,
Lydia Norton.
After this, and the yearly meeting at Salem, I parted with Friends in much love,
and came on my way homeward, visiting the meetings generally as they came in course,
also some back places, and at Swansey, Greenwich, and some other meetings,
and to Rhode Island.
Though some of these meetings were hard and suffering times, and travelling wearisome,
I was favoured with a share of peace in my own bosom.

After a little stay at Newport, and some solid times among Friends,
I took my leave and came to Kingstown meeting, and then set forward,
passing through Connecticut with Jacob Barney, who came with me as a guide,
and was a good companion.
We reached Mamarotieck, and stayed a meeting, at which were two marriages;
from thence to Long Island, where I made but a short stay,
crossed at the Narrows and Staten Island,
and got to Woodbridge meeting on the first-day of the week,
and the next day arrived at my own habitation, in about one week from Newport;
and to my great satisfaction, found my family well,
through the good providence of the Almighty.

After I came home I kept close to meetings,
and faithfully laboured in that ability God giveth;
being much concerned for the prosperity of his glorious work amongst us.
My outward endeavours were also blessed, as I kept to industry,
and I always found it best to be diligent, and not slothful in business;
yet fervent in spirit serving the Lord.
By living in this city it was my lot often to visit
the sick and those in affliction in this place,
which were heart tendering and humbling times,
which ought not to be forgotten by such who have
been humbled under the mighty hand of God,
and whom he has been pleased to relieve.
But it is much to be lamented, that too many when raised from adversity,
forget in time of prosperity the dealings of the Almighty with them;
the world and the uncertain things thereof, lead to forget what is certain to all men,
that they must die,
and after death that they are accountable to the Almighty author of their being.

[.small-break]
'''

In the year 1737, being appointed with several Friends of our monthly meeting,
to visit the families of Friends in this city,
and having a concern on my mind for the service,
I went to many places with my uncle Chalkley, and other Friends, to good satisfaction.
For some time I did not go any very distant journey, except once, as far as West River,
in Maryland, to the yearly meeting, in company with my friend Robert Jordan;
but I diligently attended meetings in this city, and sometimes those near it,
both in Pennsylvania and New Jersey; which I did in much love,
often choosing to go on foot,
having in my young years had many heavenly seasons in that way of travelling.

[.small-break]
'''

In the year 1744, it was on my mind to visit again Friends in New England,
and having the unity of our monthly meeting, and my friend Abel James for a companion,
he being a young man I much esteemed.
The latter end of the eleventh month we proceeded pretty direct to Long Island,
where we visited most of the meetings of Friends,
and the favourable presence and goodness of God being
manifested in them gave me ease of mind,
and united my heart to the faithful among them.
When clear there, we went on the main, and travelled to Newport, on Rhode Island,
where we were lovingly received among Friends.
After a short stay, we proceeded to Dartmouth, and were at a meeting there;
and so through Boston, Lynn, and Salem, having meetings,
in some of which I had satisfaction,
and was glad to see Friends with whom I had some acquaintance in the best fellowship.
The furthest place we went to in this journey was Salem;
and were at several meetings on our return to Newport,
which I hope tended to stir up the pure mind in some;
although the life of religion appeared to be at a
low ebb with many making a high profession thereof.
After several good opportunities among Friends at Newport,
we returned homewards through Connecticut,
making a short stay to rest at our friend Thomas
Franklin`'s. Thence we went to a meeting at Newtown,
on Long Island, then to New York in company with several Friends, where we had a meeting,
and then proceeded home, where I was glad to see my dear wife and family again,
it being through the kindness of divine Providence,
and they were very near and dear to me.
This journey was attended with hard travel and hard labour to my body,
also in the exercise of the gift of the ministry;
but it was in good will and much love to the people.

[.small-break]
'''

From the year 1745 to 1748, I kept much at home at our own meetings;
yet went sometimes to other meetings in Pennsylvania and New Jersey,
as in the love of truth I was drawn forth to visit them;
the Lord having a choice people in these provinces who fear his name.
My heart was often filled with endeared love to the upright-hearted seed of God,
from my first acquaintance among them;
being at times baptized and united together in the one Spirit and fellowship,
which is not in the wisdom of man, but from the power of God.

My dear wife being weakly in body, and had been in a poor state of health for some time,
departed this life in the fortieth year of her age, on the first day of the second month,
1748, and I have good reason to believe she is at rest, having before her death,
expressed that she had made her peace with the Lord.
The evident tokens of his presence in her sickness, and at her latter end,
much supported my mind in so great a trial,
and loss of so good a wife and tender mother to my children, one that loved the Truth,
and the servants of Christ, lived an innocent life, being a pattern of plainness,
a near companion, and true help-mate to me according to her capacity,
both in things spiritual and temporal.
I buried four sons before the death of their dear mother,
and in about a week after her death, I buried my youngest son,
which were very near trials; but my greatest help in these,
as well as many other afflictions that have fallen to my lot,
has been to submit to the blessed will of the Lord, who gives and takes away.
Now having two daughters left,
I was much concerned that the Almighty might be pleased to look in pity on them,
as he did in mercy on me, in my young years, and give them wisdom,
and understanding hearts, to walk before Him in his most holy fear.
For I soon found after the death of my loving wife, that I must leave them for a time,
and my habitation and near comforts of life,
for the sake of Christ and his blessed gospel, a concern increasing on my mind,
not to delay the time in which I was to perform this errand,
to go to islands and places abroad.
I made known this weighty undertaking to my dear
Friends at our monthly meeting in this city,
with which having unity, they gave me a certificate for this purpose,
in which they mentioned their prayers for my preservation through every trial and danger,
which were many before my return; but the Almighty, All-powerful Being,
delivered out of them all; glory, honour,
and eternal praise to his eminent name forever!
Before I left home, I accompanied some Friends to visit several families in this city,
which were solid and comfortable seasons.
